import assert from "node:assert/strict";
import { after,before,beforeEach,describe,it } from "node:test";
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { createPlatformDatabaseConnection } from "../../../../../shared/infrastructure/persistence/database";
import { assertSafeIntegrationTestDatabaseUrl } from "../../../infrastructure/persistence/integration-test-database-safety";
import { PostgreSqlCatalogQueryRepository } from "./postgresql-catalog-query.repository";

const testUrl=process.env.TEST_DATABASE_URL; assertSafeIntegrationTestDatabaseUrl(testUrl,process.env.DATABASE_URL);
const connection=createPlatformDatabaseConnection(testUrl!); const repository=new PostgreSqlCatalogQueryRepository(connection.database);
const visibility={retail:true,wholesale:true,availability:true,quantity:true,referenceCost:true} as const;
before(async()=>migrate(connection.database,{migrationsFolder:"drizzle"}));
beforeEach(async()=>{await connection.database.execute(sql`TRUNCATE TABLE catalog_products CASCADE`);await connection.database.execute(sql`TRUNCATE TABLE workspaces CASCADE`);await connection.database.execute(sql`
  INSERT INTO workspaces(workspace_id,company_id,workspace_code,display_name,password_recovery_policy,created_at,updated_at) VALUES
    ('workspace-a','company-a','workspace-a','A','OwnerManagedOnly','2026-01-01','2026-01-01'),('workspace-b','company-b','workspace-b','B','OwnerManagedOnly','2026-01-01','2026-01-01');
  INSERT INTO workspace_branch_references(workspace_id,branch_id,code,display_name,status,sort_order,revision,created_at,updated_at) VALUES
    ('workspace-a','branch-a','branch-a','Main','Active',0,1,'2026-01-01','2026-01-01'),('workspace-a','branch-inactive','branch-inactive','Closed','Inactive',1,1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_departments(workspace_id,department_id,code,display_name,status,sort_order,version,created_at,updated_at) VALUES
    ('workspace-a','department-computers','computers','Computers','Active',0,1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_categories(workspace_id,category_id,department_id,code,display_name,status,sort_order,version,created_at,updated_at) VALUES
    ('workspace-a','category-laptops','department-computers','laptops','Laptops','Active',0,1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_product_types(workspace_id,product_type_id,category_id,code,display_name,status,sort_order,version,created_at,updated_at) VALUES
    ('workspace-a','type-business','category-laptops','business-laptop','Business Laptop','Active',0,1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_brands(workspace_id,brand_id,code,display_name,status,sort_order,version,created_at,updated_at) VALUES
    ('workspace-a','brand-lenovo','lenovo','Lenovo','Active',0,1,'2026-01-01','2026-01-01'),('workspace-a','brand-old','old-brand','Historical Brand','Inactive',1,1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_supply_statuses(workspace_id,supply_status_id,code,display_name,status,sort_order,version,created_at,updated_at) VALUES
    ('workspace-a','status-available','available','Available','Active',0,1,'2026-01-01','2026-01-01');
  INSERT INTO workspace_condition_availability(workspace_id,condition_code,enabled,sort_order) VALUES ('workspace-a','new',true,0),('workspace-a','used',false,1);
  INSERT INTO catalog_products(workspace_id,product_id,catalog_id,lifecycle_state,revision,created_at,updated_at,has_classification,category_id,product_type_id,device_class_id,condition_id,availability_status_id,has_commercial_details,product_name,product_code,brand_id,is_highlighted,retail_price_minor,retail_price_currency,wholesale_price_minor,wholesale_price_currency) VALUES
    ('workspace-a','p-exact','catalog-a','Published',1,'2026-03-01','2026-03-01',true,'category-laptops','type-business','business','new','status-available',true,'ThinkPad X1 Carbon','QSC-X1','brand-old',false,120000,'USD',100000,'USD'),
    ('workspace-a','p-name','catalog-a','Published',1,'2026-02-01','2026-02-01',true,'category-laptops','type-business','business','new','status-available',true,'QSC X1 Sleeve','ACC-1','brand-lenovo',false,0,'USD',0,'USD'),
    ('workspace-a','p-arabic','catalog-a','Published',1,'2026-02-01','2026-02-01',true,'category-laptops','type-business','business','new','status-available',true,'حاسوب محمول للأعمال','AR-1','brand-lenovo',false,NULL,NULL,NULL,NULL),
    ('workspace-a','p-unlisted','catalog-a','Published',1,'2026-01-01','2026-01-01',true,'category-laptops','type-business','business','new','status-available',true,'ThinkPad Dock','DOCK-1','brand-lenovo',false,9007199254740991,'USD',15000,'USD'),
    ('workspace-b','p-foreign','catalog-b','Published',1,'2026-04-01','2026-04-01',false,NULL,NULL,NULL,NULL,NULL,false,NULL,NULL,NULL,false,NULL,NULL,NULL,NULL);
  INSERT INTO catalog_branch_product_listings(workspace_id,branch_id,product_id,listing_status,revision,created_at,updated_at) VALUES
    ('workspace-a','branch-a','p-exact','Listed',1,'2026-01-01','2026-01-01'),('workspace-a','branch-a','p-name','Listed',1,'2026-01-01','2026-01-01'),('workspace-a','branch-a','p-arabic','Listed',1,'2026-01-01','2026-01-01'),('workspace-a','branch-a','p-unlisted','Unlisted',1,'2026-01-01','2026-01-01');
  INSERT INTO inventory_balances(workspace_id,branch_id,product_id,on_hand_quantity,reserved_quantity,damaged_quantity,revision,updated_at) VALUES ('workspace-a','branch-a','p-exact',10,2,1,1,'2026-01-01'),('workspace-a','branch-a','p-name',0,0,0,1,'2026-01-01');
  INSERT INTO catalog_product_branch_price_overrides(workspace_id,branch_id,product_id,price_type,amount_minor,currency,revision,created_at,updated_at) VALUES ('workspace-a','branch-a','p-exact','Retail',125000,'USD',1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_product_reference_costs(workspace_id,product_id,amount_minor,currency,revision,created_at,updated_at) VALUES ('workspace-a','p-exact',90000,'USD',1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_product_images(workspace_id,product_id,product_image_id,storage_key,position,is_main,alt_text) VALUES ('workspace-a','p-exact','media-main','internal/never/exposed.webp',0,true,'Front');
  INSERT INTO catalog_specification_definitions(workspace_id,specification_definition_id,code,display_name,status,sort_order,version,created_at,updated_at,value_type,unit) VALUES
    ('workspace-a','spec-ram','ram','RAM','Inactive',0,1,'2026-01-01','2026-01-01','Number','GB'),
    ('workspace-a','spec-storage','storage','Storage','Active',1,1,'2026-01-01','2026-01-01','Number','GB'),
    ('workspace-b','spec-ram','ram','Foreign RAM','Active',0,1,'2026-01-01','2026-01-01','Text',NULL);
  INSERT INTO catalog_specification_templates(workspace_id,specification_template_id,product_type_id,version,created_at,updated_at) VALUES ('workspace-a','template-business','type-business',1,'2026-01-01','2026-01-01');
  INSERT INTO catalog_specification_template_entries(workspace_id,specification_template_id,specification_definition_id,sort_order,required) VALUES ('workspace-a','template-business','spec-ram',0,true),('workspace-a','template-business','spec-storage',1,false);
  INSERT INTO catalog_product_specification_values(workspace_id,product_id,specification_field_id,position,value_type,number_value) VALUES ('workspace-a','p-exact','spec-ram',1,'number','16'),('workspace-a','p-exact','spec-storage',0,'number','512');
`)});
after(async()=>connection.close());

const search=(overrides:Partial<Parameters<typeof repository.search>[0]>={})=>repository.search({workspaceId:"workspace-a",branchId:"branch-a",searchText:"",filters:{lifecycle:"Published",listing:"Listed"},sort:"newest",cursor:null,limit:24,visibility,...overrides});
describe("PostgreSQL catalog query repository",()=>{
  it("isolates tenants and applies listed/stock/effective-price filters",async()=>{const rows=await search({filters:{lifecycle:"Published",listing:"Listed",stock:"InStock",minRetailPrice:BigInt(125000),retailCurrency:"USD"}});assert.deepEqual(rows.map((row)=>row.product.productId),["p-exact"]);assert.equal(rows[0]?.product.inventory.available,BigInt(7));assert.equal(rows[0]?.product.retail?.amountMinor,BigInt(125000));assert.equal(rows.some((row)=>row.product.productId==="p-foreign"),false);});
  it("ranks exact code above name/reference matches deterministically",async()=>{const rows=await search({searchText:"QSC-X1",sort:"relevance"});assert.equal(rows[0]?.product.productId,"p-exact");const again=await search({searchText:"QSC-X1",sort:"relevance"});assert.deepEqual(again.map((row)=>row.product.productId),rows.map((row)=>row.product.productId));});
  it("searches English case-insensitively, reference labels, Arabic, and trigram typos",async()=>{for(const term of ["thinkpad","Historical Brand","Laptops","Business Laptop","حاسوب","ThnkPad"]){const rows=await search({searchText:term,sort:"relevance"});assert.ok(rows.length>0,term);}});
  it("combines hierarchy/classification/listing/stock filters",async()=>{const filters={lifecycle:"Published" as const,listing:"Listed" as const,departmentId:"department-computers",categoryId:"category-laptops",productTypeId:"type-business",brandId:"brand-lenovo",deviceClass:"business" as const,condition:"new" as const,supplyStatusId:"status-available",stock:"OutOfStock" as const};const rows=await search({filters});assert.deepEqual(rows.map((row)=>row.product.productId).sort(),["p-arabic","p-name"]);const unlisted=await search({filters:{lifecycle:"Published",listing:"Unlisted"}});assert.deepEqual(unlisted.map((row)=>row.product.productId),["p-unlisted"]);});
  it("makes Brand, Category, and Product Type prefixes reachable candidates",async()=>{for(const term of ["Len","Lap","Bus"]){const rows=await search({searchText:term,sort:"relevance"});assert.ok(rows.length>0,term);}});
  it("implements every fixed sort with explicit null-price ordering and bigint fidelity",async()=>{for(const sort of ["newest","name-asc","name-desc"] as const)assert.ok((await search({sort})).length>=3);for(const sort of ["retail-price-asc","retail-price-desc"] as const){const rows=await search({sort,filters:{lifecycle:"Published",listing:"Listed",retailCurrency:"USD"}});assert.equal(rows.at(-1)?.product.productId,"p-arabic");}const zero=(await search({sort:"retail-price-asc",filters:{lifecycle:"Published",listing:"Listed",retailCurrency:"USD"}}))[0];assert.equal(zero?.product.retail?.amountMinor,BigInt(0));const maximum=await search({filters:{lifecycle:"Published",listing:"Unlisted"}});assert.equal(maximum[0]?.product.retail?.amountMinor,BigInt("9007199254740991"));});
  it("uses parameterized input and stable cursor positions",async()=>{assert.equal((await search({searchText:"%' OR true --",sort:"relevance"})).length,0);const first=await search({limit:1});assert.equal(first.length,1);const second=await search({cursor:first[0]!.cursor,limit:2});assert.equal(second.some((row)=>row.product.productId===first[0]!.product.productId),false);});
  it("walks duplicate newest keys without duplicates or skipped rows",async()=>{const found:string[]=[];let cursor:Parameters<typeof repository.search>[0]["cursor"]=null;for(;;){const rows=await search({sort:"newest",cursor,limit:1});if(!rows[0])break;found.push(rows[0].product.productId);cursor=rows[0].cursor;}assert.deepEqual(found,["p-exact","p-arabic","p-name"]);assert.equal(new Set(found).size,found.length);});
  it("renders persisted historical specifications after current template membership changes",async()=>{const beforeValue=await connection.database.execute<Record<string,unknown>>(sql`SELECT position,value_type,number_value FROM catalog_product_specification_values WHERE workspace_id='workspace-a' AND product_id='p-exact' AND specification_field_id='spec-ram'`);await connection.database.execute(sql`DELETE FROM catalog_specification_template_entries WHERE workspace_id='workspace-a' AND specification_template_id='template-business' AND specification_definition_id='spec-ram'`);const details=await repository.getDetails({workspaceId:"workspace-a",productId:"p-exact",branchId:"branch-a",visibility});const again=await repository.getDetails({workspaceId:"workspace-a",productId:"p-exact",branchId:"branch-a",visibility});assert.equal(details?.classification.brand?.displayName,"Historical Brand");assert.equal(details?.media[0]?.mediaId,"media-main");assert.equal(details?.media.some((item)=>"storageKey" in item),false);assert.deepEqual(details?.specifications.map((item)=>item.specificationDefinitionId),["spec-storage","spec-ram"]);const ram=details?.specifications.find((item)=>item.specificationDefinitionId==="spec-ram");assert.deepEqual(ram,{specificationDefinitionId:"spec-ram",displayName:"RAM",valueType:"Number",unit:"GB",value:"16",sortOrder:1});assert.deepEqual(again?.specifications,details?.specifications);const afterValue=await connection.database.execute<Record<string,unknown>>(sql`SELECT position,value_type,number_value FROM catalog_product_specification_values WHERE workspace_id='workspace-a' AND product_id='p-exact' AND specification_field_id='spec-ram'`);assert.deepEqual(afterValue.rows,beforeValue.rows);const options=await repository.getFilterOptions("workspace-a");assert.deepEqual(options.brands.map((brand)=>brand.id),["brand-lenovo"]);assert.deepEqual(options.enabledConditions,["new"]);});
  it("does not expose active hierarchy children beneath an inactive ancestor",async()=>{await connection.database.execute(sql`UPDATE catalog_departments SET status='Inactive',version=version+1,updated_at='2026-02-01' WHERE workspace_id='workspace-a' AND department_id='department-computers'`);const options=await repository.getFilterOptions("workspace-a");assert.deepEqual(options.departments,[]);assert.deepEqual(options.categories,[]);assert.deepEqual(options.productTypes,[]);assert.equal(await repository.hierarchyIsValid("workspace-a",{categoryId:"category-laptops"}),false);assert.equal(await repository.hierarchyIsValid("workspace-a",{productTypeId:"type-business"}),false);});
  it("has migration-managed query indexes and an actual newest-sort eligible plan",async()=>{await connection.database.execute(sql`INSERT INTO catalog_products(workspace_id,product_id,catalog_id,lifecycle_state,revision,created_at,updated_at,has_classification,has_commercial_details,is_highlighted) SELECT 'workspace-a','perf-'||value,'catalog-a','Published',1,'2025-01-01'::timestamptz + value*interval '1 second','2025-01-01'::timestamptz + value*interval '1 second',false,false,false FROM generate_series(1,5000) value`);await connection.database.execute(sql`ANALYZE catalog_products`);const plan=await connection.database.execute<Record<string,string>>(sql`EXPLAIN (COSTS OFF) SELECT product_id FROM catalog_products WHERE workspace_id='workspace-a' AND lifecycle_state='Published' ORDER BY created_at DESC,product_id ASC LIMIT 24`);assert.match(plan.rows.map((row)=>Object.values(row)[0]).join("\n"),/catalog_products_query_newest_idx/u);const extension=await connection.database.execute<{found:boolean}>(sql`SELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_trgm') AS found`);assert.equal(extension.rows[0]?.found,true);const referenceTrigramIndexes=await connection.database.execute<{count:string}>(sql`SELECT count(*)::text AS count FROM pg_indexes WHERE indexname IN ('catalog_brands_display_name_trgm_idx','catalog_categories_display_name_trgm_idx','catalog_product_types_display_name_trgm_idx')`);assert.equal(referenceTrigramIndexes.rows[0]?.count,"0");});
});
