import { randomUUID } from "node:crypto";
import { and, eq } from "drizzle-orm";
import type { PlatformDatabase } from "../../../../../shared/infrastructure/persistence/database";
import { securityAuditEvents } from "../../../../../shared/audit/infrastructure/persistence/schema";
import { workspaceBranchReferences } from "../../../../workspace/infrastructure/persistence/schema";
import { catalogBranchProductListings, catalogProductBranchPriceOverrides, catalogProductReferenceCosts, catalogProducts, workspaceCurrencyAvailability } from "../../../infrastructure/persistence/schema";
import { inventoryBalances } from "../../../../inventory/infrastructure/persistence/schema";
import type { BranchPriceOverride, BranchProductListingStatus, PriceType, PriceValue } from "../../domain/branch-product";
import type { BranchProductAuditRepository, BranchProductInventoryReadRepository, BranchProductListingRepository, BranchProductScopeRepository, BranchProductTransactionContext, BranchProductUnitOfWork, ProductPricingRepository } from "../../ports/branch-product-unit-of-work.port";

class PostgreSqlBranchProductScopeRepository implements BranchProductScopeRepository {
  constructor(private readonly database: PlatformDatabase) {}
  async findBranch(workspaceId: string, branchId: string) { const rows = await this.database.select({ status: workspaceBranchReferences.status }).from(workspaceBranchReferences).where(and(eq(workspaceBranchReferences.workspaceId, workspaceId), eq(workspaceBranchReferences.branchId, branchId))).limit(1); return rows[0] ? { status: rows[0].status as "Active" | "Inactive" } : null; }
  async findProduct(workspaceId: string, productId: string) { const rows = await this.database.select({ lifecycleState: catalogProducts.lifecycleState, revision: catalogProducts.revision }).from(catalogProducts).where(and(eq(catalogProducts.workspaceId, workspaceId), eq(catalogProducts.productId, productId))).limit(1); return rows[0] ?? null; }
  async isCurrencyEnabled(workspaceId: string, currency: string) { const rows = await this.database.select({ enabled: workspaceCurrencyAvailability.enabled }).from(workspaceCurrencyAvailability).where(and(eq(workspaceCurrencyAvailability.workspaceId, workspaceId), eq(workspaceCurrencyAvailability.currencyCode, currency), eq(workspaceCurrencyAvailability.enabled, true))).limit(1); return rows.length === 1; }
}

class PostgreSqlBranchProductListingRepository implements BranchProductListingRepository {
  constructor(private readonly database: PlatformDatabase) {}
  async get(workspaceId: string, branchId: string, productId: string) { const rows = await this.database.select().from(catalogBranchProductListings).where(and(eq(catalogBranchProductListings.workspaceId, workspaceId), eq(catalogBranchProductListings.branchId, branchId), eq(catalogBranchProductListings.productId, productId))).limit(1); const row = rows[0]; return row ? { status: row.listingStatus as BranchProductListingStatus, revision: row.revision, createdAt: row.createdAt, updatedAt: row.updatedAt } : null; }
  async set(input: { readonly workspaceId: string; readonly branchId: string; readonly productId: string; readonly status: BranchProductListingStatus; readonly expectedRevision: number; readonly now: Date }) { if (input.expectedRevision === 0) { const rows = await this.database.insert(catalogBranchProductListings).values({ workspaceId: input.workspaceId, branchId: input.branchId, productId: input.productId, listingStatus: input.status, revision: 1, createdAt: input.now, updatedAt: input.now }).onConflictDoNothing().returning(); const row = rows[0]; return row ? { status: row.listingStatus as BranchProductListingStatus, revision: row.revision, createdAt: row.createdAt, updatedAt: row.updatedAt } : null; } const rows = await this.database.update(catalogBranchProductListings).set({ listingStatus: input.status, revision: input.expectedRevision + 1, updatedAt: input.now }).where(and(eq(catalogBranchProductListings.workspaceId, input.workspaceId), eq(catalogBranchProductListings.branchId, input.branchId), eq(catalogBranchProductListings.productId, input.productId), eq(catalogBranchProductListings.revision, input.expectedRevision))).returning(); const row = rows[0]; return row ? { status: row.listingStatus as BranchProductListingStatus, revision: row.revision, createdAt: row.createdAt, updatedAt: row.updatedAt } : null; }
}

class PostgreSqlBranchProductInventoryReadRepository implements BranchProductInventoryReadRepository {
  constructor(private readonly database: PlatformDatabase) {}
  async getBalance(workspaceId: string, branchId: string, productId: string) { const rows = await this.database.select().from(inventoryBalances).where(and(eq(inventoryBalances.workspaceId, workspaceId), eq(inventoryBalances.branchId, branchId), eq(inventoryBalances.productId, productId))).limit(1); const row = rows[0]; return row ? { onHand: row.onHandQuantity, reserved: row.reservedQuantity, damaged: row.damagedQuantity, revision: row.revision, updatedAt: row.updatedAt } : null; }
}

const override = (row: typeof catalogProductBranchPriceOverrides.$inferSelect): BranchPriceOverride => Object.freeze({ workspaceId: row.workspaceId, branchId: row.branchId, productId: row.productId, priceType: row.priceType as PriceType, amountMinor: row.amountMinor, currency: row.currency, revision: row.revision, createdAt: row.createdAt, updatedAt: row.updatedAt });
class PostgreSqlProductPricingRepository implements ProductPricingRepository {
  constructor(private readonly database: PlatformDatabase) {}
  async getBase(workspaceId: string, productId: string, priceType: PriceType): Promise<PriceValue | null> { if (priceType === "ReferenceCost") { const rows = await this.database.select().from(catalogProductReferenceCosts).where(and(eq(catalogProductReferenceCosts.workspaceId, workspaceId), eq(catalogProductReferenceCosts.productId, productId))).limit(1); const row = rows[0]; return row ? { amountMinor: row.amountMinor, currency: row.currency, revision: row.revision } : null; } const rows = await this.database.select({ retailAmount: catalogProducts.retailPriceMinor, retailCurrency: catalogProducts.retailPriceCurrency, wholesaleAmount: catalogProducts.wholesalePriceMinor, wholesaleCurrency: catalogProducts.wholesalePriceCurrency, revision: catalogProducts.revision }).from(catalogProducts).where(and(eq(catalogProducts.workspaceId, workspaceId), eq(catalogProducts.productId, productId))).limit(1); const row = rows[0]; if (!row) return null; const amount = priceType === "Retail" ? row.retailAmount : row.wholesaleAmount; const currency = priceType === "Retail" ? row.retailCurrency : row.wholesaleCurrency; return amount === null || currency === null ? null : { amountMinor: BigInt(amount), currency, revision: row.revision }; }
  async setBase(input: { readonly workspaceId: string; readonly productId: string; readonly priceType: PriceType; readonly amountMinor: bigint; readonly currency: string; readonly expectedRevision: number; readonly now: Date }): Promise<PriceValue | null> { if (input.priceType === "ReferenceCost") { if (input.expectedRevision === 0) { const rows = await this.database.insert(catalogProductReferenceCosts).values({ workspaceId: input.workspaceId, productId: input.productId, amountMinor: input.amountMinor, currency: input.currency, revision: 1, createdAt: input.now, updatedAt: input.now }).onConflictDoNothing().returning(); const row = rows[0]; return row ? { amountMinor: row.amountMinor, currency: row.currency, revision: row.revision } : null; } const rows = await this.database.update(catalogProductReferenceCosts).set({ amountMinor: input.amountMinor, currency: input.currency, revision: input.expectedRevision + 1, updatedAt: input.now }).where(and(eq(catalogProductReferenceCosts.workspaceId, input.workspaceId), eq(catalogProductReferenceCosts.productId, input.productId), eq(catalogProductReferenceCosts.revision, input.expectedRevision))).returning(); const row = rows[0]; return row ? { amountMinor: row.amountMinor, currency: row.currency, revision: row.revision } : null; } const amount = Number(input.amountMinor); const set = input.priceType === "Retail" ? { retailPriceMinor: amount, retailPriceCurrency: input.currency } : { wholesalePriceMinor: amount, wholesalePriceCurrency: input.currency }; const rows = await this.database.update(catalogProducts).set({ ...set, hasCommercialDetails: true, revision: input.expectedRevision + 1, updatedAt: input.now }).where(and(eq(catalogProducts.workspaceId, input.workspaceId), eq(catalogProducts.productId, input.productId), eq(catalogProducts.revision, input.expectedRevision))).returning({ revision: catalogProducts.revision }); return rows[0] ? { amountMinor: input.amountMinor, currency: input.currency, revision: rows[0].revision } : null; }
  async clearBase(input: { readonly workspaceId: string; readonly productId: string; readonly priceType: PriceType; readonly expectedRevision: number; readonly now: Date }) { if (input.priceType === "ReferenceCost") { const rows = await this.database.delete(catalogProductReferenceCosts).where(and(eq(catalogProductReferenceCosts.workspaceId, input.workspaceId), eq(catalogProductReferenceCosts.productId, input.productId), eq(catalogProductReferenceCosts.revision, input.expectedRevision))).returning({ productId: catalogProductReferenceCosts.productId }); return rows.length === 1; } const set = input.priceType === "Retail" ? { retailPriceMinor: null, retailPriceCurrency: null } : { wholesalePriceMinor: null, wholesalePriceCurrency: null }; const rows = await this.database.update(catalogProducts).set({ ...set, revision: input.expectedRevision + 1, updatedAt: input.now }).where(and(eq(catalogProducts.workspaceId, input.workspaceId), eq(catalogProducts.productId, input.productId), eq(catalogProducts.revision, input.expectedRevision))).returning({ productId: catalogProducts.productId }); return rows.length === 1; }
  async getOverride(workspaceId: string, branchId: string, productId: string, priceType: PriceType) { const rows = await this.database.select().from(catalogProductBranchPriceOverrides).where(and(eq(catalogProductBranchPriceOverrides.workspaceId, workspaceId), eq(catalogProductBranchPriceOverrides.branchId, branchId), eq(catalogProductBranchPriceOverrides.productId, productId), eq(catalogProductBranchPriceOverrides.priceType, priceType))).limit(1); return rows[0] ? override(rows[0]) : null; }
  async setOverride(input: { readonly workspaceId: string; readonly branchId: string; readonly productId: string; readonly priceType: PriceType; readonly amountMinor: bigint; readonly currency: string; readonly expectedRevision: number; readonly now: Date }) { if (input.expectedRevision === 0) { const rows = await this.database.insert(catalogProductBranchPriceOverrides).values({ workspaceId: input.workspaceId, branchId: input.branchId, productId: input.productId, priceType: input.priceType, amountMinor: input.amountMinor, currency: input.currency, revision: 1, createdAt: input.now, updatedAt: input.now }).onConflictDoNothing().returning(); return rows[0] ? override(rows[0]) : null; } const rows = await this.database.update(catalogProductBranchPriceOverrides).set({ amountMinor: input.amountMinor, currency: input.currency, revision: input.expectedRevision + 1, updatedAt: input.now }).where(and(eq(catalogProductBranchPriceOverrides.workspaceId, input.workspaceId), eq(catalogProductBranchPriceOverrides.branchId, input.branchId), eq(catalogProductBranchPriceOverrides.productId, input.productId), eq(catalogProductBranchPriceOverrides.priceType, input.priceType), eq(catalogProductBranchPriceOverrides.revision, input.expectedRevision))).returning(); return rows[0] ? override(rows[0]) : null; }
  async clearOverride(input: { readonly workspaceId: string; readonly branchId: string; readonly productId: string; readonly priceType: PriceType; readonly expectedRevision: number }) { const rows = await this.database.delete(catalogProductBranchPriceOverrides).where(and(eq(catalogProductBranchPriceOverrides.workspaceId, input.workspaceId), eq(catalogProductBranchPriceOverrides.branchId, input.branchId), eq(catalogProductBranchPriceOverrides.productId, input.productId), eq(catalogProductBranchPriceOverrides.priceType, input.priceType), eq(catalogProductBranchPriceOverrides.revision, input.expectedRevision))).returning({ productId: catalogProductBranchPriceOverrides.productId }); return rows.length === 1; }
}

class PostgreSqlBranchProductAuditRepository implements BranchProductAuditRepository { constructor(private readonly database: PlatformDatabase) {} async append(input: Parameters<BranchProductAuditRepository["append"]>[0]) { await this.database.insert(securityAuditEvents).values({ workspaceId: input.workspaceId, auditId: randomUUID(), eventType: input.eventType, actorId: input.actorId, subjectActorId: null, resultCode: "Succeeded", metadata: input.metadata, occurredAt: input.occurredAt }); } }
export class PostgreSqlBranchProductUnitOfWork implements BranchProductUnitOfWork { constructor(private readonly database: PlatformDatabase) {} execute<T>(work: (context: BranchProductTransactionContext) => Promise<T>): Promise<T> { return this.database.transaction(async (transaction) => { const database = transaction as unknown as PlatformDatabase; return work(Object.freeze({ scope: new PostgreSqlBranchProductScopeRepository(database), listings: new PostgreSqlBranchProductListingRepository(database), pricing: new PostgreSqlProductPricingRepository(database), inventory: new PostgreSqlBranchProductInventoryReadRepository(database), audit: new PostgreSqlBranchProductAuditRepository(database) })); }); } }
