ALTER TABLE "catalog_product_entry_submission_media_operations" DROP CONSTRAINT "catalog_product_entry_submission_media_operations_type";--> statement-breakpoint
ALTER TABLE "catalog_product_entry_submission_media_operations" DROP CONSTRAINT "catalog_product_entry_submission_media_operations_shape";--> statement-breakpoint
CREATE UNIQUE INDEX "catalog_product_entry_submission_media_operations_cover_uq" ON "catalog_product_entry_submission_media_operations" USING btree ("workspace_id","submission_id") WHERE "catalog_product_entry_submission_media_operations"."selected_as_cover" = true;--> statement-breakpoint
ALTER TABLE "catalog_product_entry_submission_media_operations" ADD CONSTRAINT "catalog_product_entry_submission_media_operations_type" CHECK ("catalog_product_entry_submission_media_operations"."operation_type" IN ('Add','Replace','Remove','Reorder','SetCover'));--> statement-breakpoint
ALTER TABLE "catalog_product_entry_submission_media_operations" ADD CONSTRAINT "catalog_product_entry_submission_media_operations_shape" CHECK (
      ("catalog_product_entry_submission_media_operations"."operation_type" = 'Add' AND "catalog_product_entry_submission_media_operations"."media_id" IS NULL AND "catalog_product_entry_submission_media_operations"."expected_source_sha256" ~ '^[a-f0-9]{64}$' AND "catalog_product_entry_submission_media_operations"."expected_source_byte_length" IS NOT NULL) OR
      ("catalog_product_entry_submission_media_operations"."operation_type" = 'Replace' AND btrim("catalog_product_entry_submission_media_operations"."media_id") <> '' AND "catalog_product_entry_submission_media_operations"."expected_source_sha256" ~ '^[a-f0-9]{64}$' AND "catalog_product_entry_submission_media_operations"."expected_source_byte_length" IS NOT NULL) OR
      ("catalog_product_entry_submission_media_operations"."operation_type" = 'Remove' AND btrim("catalog_product_entry_submission_media_operations"."media_id") <> '' AND "catalog_product_entry_submission_media_operations"."expected_source_sha256" IS NULL AND "catalog_product_entry_submission_media_operations"."expected_source_byte_length" IS NULL AND "catalog_product_entry_submission_media_operations"."requested_display_order" IS NULL AND "catalog_product_entry_submission_media_operations"."final_order" IS NULL AND "catalog_product_entry_submission_media_operations"."selected_as_cover" = false) OR
      ("catalog_product_entry_submission_media_operations"."operation_type" = 'Reorder' AND btrim("catalog_product_entry_submission_media_operations"."media_id") <> '' AND "catalog_product_entry_submission_media_operations"."expected_source_sha256" IS NULL AND "catalog_product_entry_submission_media_operations"."expected_source_byte_length" IS NULL AND "catalog_product_entry_submission_media_operations"."requested_display_order" IS NOT NULL AND "catalog_product_entry_submission_media_operations"."final_order" = "catalog_product_entry_submission_media_operations"."requested_display_order" AND "catalog_product_entry_submission_media_operations"."selected_as_cover" = false) OR
      ("catalog_product_entry_submission_media_operations"."operation_type" = 'SetCover' AND btrim("catalog_product_entry_submission_media_operations"."media_id") <> '' AND "catalog_product_entry_submission_media_operations"."expected_source_sha256" IS NULL AND "catalog_product_entry_submission_media_operations"."expected_source_byte_length" IS NULL AND "catalog_product_entry_submission_media_operations"."requested_display_order" IS NULL AND "catalog_product_entry_submission_media_operations"."final_order" IS NULL AND "catalog_product_entry_submission_media_operations"."selected_as_cover" = true)
    );
