import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { TrustedActorContext } from "../../../../shared/auth/trusted-actor-context";
import type { ProductMediaReaderPort } from "../../media/ports/product-media-reader.port";
import { catalogQueryFingerprint, type CatalogCursorPosition, type CatalogFilterOptionsProjection, type CatalogMediaStorageProjection, type CatalogProductDetailsProjection, type CatalogProductSearchRow, type CatalogSort } from "../domain/catalog-query";
import type { CatalogQueryRepository, CatalogSearchRepositoryQuery } from "../ports/catalog-query-repository.port";
import { DownloadCatalogProductMediaUseCase, GetCatalogFilterOptionsUseCase, GetCatalogProductDetailsUseCase, SearchCatalogProductsUseCase, SearchOperationalProductsUseCase } from "./catalog-query.use-cases";

const actor=(permissions:readonly string[]=[],role:"Owner"|"Staff"="Staff",workspaceId="workspace-a"):TrustedActorContext=>({workspaceId,actorId:"actor-a",role,permissions,branchScope:{type:"SelectedBranches",branchIds:["branch-a"]},authorizationVersion:1});
const projection=(id:string):CatalogProductDetailsProjection=>({productId:id,productCode:"QSC-1",productName:"ThinkPad X1",lifecycle:"Published",createdAt:new Date("2026-01-01T00:00:00Z"),updatedAt:new Date("2026-01-02T00:00:00Z"),classification:{department:{id:"d",displayName:"Computers"},category:{id:"c",displayName:"Laptops"},productType:{id:"t",displayName:"Business laptop"},brand:{id:"b",displayName:"Lenovo"},deviceClass:"business",condition:"new",supplyStatus:{id:"s",displayName:"Available"}},mainMedia:{mediaId:"m",altText:"Front",position:0,isMain:true},listingStatus:"Listed",inventory:{available:BigInt(7),onHand:BigInt(10),reserved:BigInt(2),damaged:BigInt(1)},retail:{amountMinor:BigInt(125000),currency:"USD",source:"BranchOverride"},wholesale:{amountMinor:BigInt(110000),currency:"USD",source:"WorkspaceBase"},referenceCost:{amountMinor:BigInt(90000),currency:"USD",source:"WorkspaceBase"},media:[{mediaId:"m",altText:"Front",position:0,isMain:true}],specifications:[{specificationDefinitionId:"ram",displayName:"RAM",valueType:"Number",unit:"GB",value:"16",sortOrder:0}]});
class MemoryRepository implements CatalogQueryRepository { lastSearch?:CatalogSearchRepositoryQuery; lastAllowedBranchIds?:readonly string[]|null; rows:CatalogProductSearchRow[]=[{product:projection("p1"),cursor:{productId:"p1",value:"1000"}},{product:projection("p2"),cursor:{productId:"p2",value:"900"}}]; details:CatalogProductDetailsProjection|null=projection("p1"); media:CatalogMediaStorageProjection|null=null; branch=true; hierarchy=true; invocations=0;
  async branchExists(){this.invocations+=1;return this.branch} async hierarchyIsValid(){this.invocations+=1;return this.hierarchy} async search(query:CatalogSearchRepositoryQuery):Promise<readonly CatalogProductSearchRow[]>{this.invocations+=1;this.lastSearch=query;return this.rows.map((row,index)=>({...row,cursor:query.sort==="relevance"?row.cursor:query.sort==="newest"?{productId:row.product.productId,value:row.product.createdAt.toISOString()}:query.sort.startsWith("name")?{productId:row.product.productId,value:(row.product.productName??"").toLowerCase()}:{productId:row.product.productId,value:String(125000+index),nullRank:0 as const}}))} async getDetails(){this.invocations+=1;return this.details} async getFilterOptions(_workspaceId:string,allowedBranchIds:readonly string[]|null):Promise<CatalogFilterOptionsProjection>{this.invocations+=1;this.lastAllowedBranchIds=allowedBranchIds;return {departments:[],categories:[],productTypes:[],brands:[],supplyStatuses:[],branches:[{id:"branch-a",displayName:"Main"}],enabledConditions:[],enabledCurrencies:["USD"]}} async getMedia(){return this.media}
}
const tamperedCursor=(sort:CatalogSort,position:CatalogCursorPosition,retail=false)=>{const visibility={retail,wholesale:false,availability:false,quantity:false,referenceCost:false};const queryFingerprint=catalogQueryFingerprint({searchText:sort==="relevance"?"x":"",branchId:null,filters:{lifecycle:"Published",...(retail?{retailCurrency:"USD"}:{})},sort,visibility});return Buffer.from(JSON.stringify({version:1,sort,queryFingerprint,...position}),"utf8").toString("base64url")};
describe("Catalog query application",()=>{
  it("requires catalog view and hides foreign branch scope",async()=>{const repo=new MemoryRepository();assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(),input:{}}),{ok:false,error:"Forbidden"});assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{branchId:"branch-b"}}),{ok:false,error:"BranchNotFound"});});
  it("defaults branch searches to listed published products",async()=>{const repo=new MemoryRepository();await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{branchId:"branch-a",limit:1}});assert.equal(repo.lastSearch?.filters.listing,"Listed");assert.deepEqual(repo.lastSearch?.lifecycleScope,{type:"Exact",lifecycle:"Published"});});
  it("keeps the ordinary default fingerprint byte-compatible with the A2 baseline",()=>{assert.equal(catalogQueryFingerprint({searchText:"",branchId:null,filters:{lifecycle:"Published"},sort:"newest",visibility:{retail:false,wholesale:false,availability:false,quantity:false,referenceCost:false}}),"1fffc93da3f5d5254f7d60b5b3bc16b7d65e99f3adb0763c952672c8a0be009b");});
  it("requires edit authority for non-listed discovery",async()=>{const repo=new MemoryRepository();const result=await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{branchId:"branch-a",listing:"Any"}});assert.deepEqual(result,{ok:false,error:"Forbidden"});});
  it("rejects invalid hierarchy, price currency ambiguity, and unbound cursors",async()=>{const repo=new MemoryRepository();repo.hierarchy=false;assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{categoryId:"foreign"}}),{ok:false,error:"InvalidQuery"});repo.hierarchy=true;assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view","pricing.view"]),input:{minRetailPrice:"1"}}),{ok:false,error:"InvalidQuery"});const first=await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{q:"x",limit:1}});assert.ok(first.ok);assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{q:"changed",cursor:first.ok?first.value.nextCursor!:""}}),{ok:false,error:"InvalidCursor"});});
  it("returns only a derived availability state to availability viewers on cards and details",async()=>{const repo=new MemoryRepository();const permissions=["catalog.products.view","inventory.availability.view"];const cards=await new SearchCatalogProductsUseCase(repo).execute({context:actor(permissions),input:{q:"ThinkPad",branchId:"branch-a",stock:"InStock",limit:1}});assert.ok(cards.ok);if(!cards.ok)return;assert.ok(cards.value.nextCursor);assert.equal(cards.value.items[0]?.availability,"InStock");assert.equal("inventory" in cards.value.items[0]!,false);assert.equal("retail" in cards.value.items[0]!,false);assert.equal("referenceCost" in cards.value.items[0]!,false);assert.equal(repo.lastSearch?.filters.stock,"InStock");const details=await new GetCatalogProductDetailsUseCase(repo).execute({context:actor(permissions),productId:"p1",branchId:"branch-a"});assert.ok(details.ok);if(details.ok){assert.equal(details.value.availability,"InStock");assert.equal("inventory" in details.value,false);}});
  it("returns exact quantities on cards and details only with quantity authority",async()=>{const repo=new MemoryRepository();const context=actor(["catalog.products.view","inventory.quantity.view"]);const cards=await new SearchCatalogProductsUseCase(repo).execute({context,input:{branchId:"branch-a"}});assert.ok(cards.ok);if(cards.ok){assert.equal(cards.value.items[0]?.availability,"InStock");assert.deepEqual(cards.value.items[0]?.inventory,{available:"7",onHand:"10",reserved:"2",damaged:"1"});}const details=await new GetCatalogProductDetailsUseCase(repo).execute({context,productId:"p1",branchId:"branch-a"});assert.ok(details.ok);if(details.ok)assert.deepEqual(details.value.inventory,{available:"7",onHand:"10",reserved:"2",damaged:"1"});});
  it("returns decimal-string money and reference cost only on authorized details",async()=>{const repo=new MemoryRepository();const result=await new GetCatalogProductDetailsUseCase(repo).execute({context:actor(["catalog.products.view","pricing.view","pricing.wholesale.view","referenceCost.view","inventory.quantity.view"]),productId:"p1",branchId:"branch-a"});assert.ok(result.ok);if(!result.ok)return;assert.equal(result.value.retail?.amountMinor,"125000");assert.equal(result.value.wholesale?.amountMinor,"110000");assert.equal(result.value.referenceCost?.amountMinor,"90000");assert.equal(result.value.inventory?.onHand,"10");});
  it("enforces page limits and never includes reference cost in cards",async()=>{const repo=new MemoryRepository();assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{limit:61}}),{ok:false,error:"InvalidQuery"});const result=await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view","pricing.view","pricing.wholesale.view","referenceCost.view"]),input:{}});assert.ok(result.ok);if(!result.ok)return;assert.equal(repo.lastSearch?.limit,25);assert.equal(result.value.items[0]?.retail?.amountMinor,"125000");assert.equal(result.value.items[0]?.wholesale?.amountMinor,"110000");assert.equal("referenceCost" in result.value.items[0]!,false);});
  it("accepts the maximum page, rejects malformed and changed-sort cursors, and ends with null cursor",async()=>{const repo=new MemoryRepository();repo.rows=[repo.rows[0]!];const final=await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{limit:60}});assert.ok(final.ok);if(final.ok)assert.equal(final.value.nextCursor,null);assert.equal(repo.lastSearch?.limit,61);assert.deepEqual(await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view"]),input:{cursor:"not-a-cursor"}}),{ok:false,error:"InvalidCursor"});const first=await new SearchCatalogProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.products.view"]),input:{q:"x",limit:1}});assert.ok(first.ok);if(first.ok)assert.deepEqual(await new SearchCatalogProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.products.view"]),input:{q:"x",sort:"newest",cursor:first.value.nextCursor!}}),{ok:false,error:"InvalidCursor"});});
  it("rejects every tampered sort tuple before invoking the repository",async()=>{const cases:readonly {sort:CatalogSort;position:CatalogCursorPosition;retail?:boolean}[]=[
    {sort:"relevance",position:{productId:"p1",value:"text"}},{sort:"relevance",position:{productId:"p1",value:"NaN"}},{sort:"relevance",position:{productId:"p1",value:"Infinity"}},{sort:"relevance",position:{productId:"p1",value:"-Infinity"}},
    {sort:"newest",position:{productId:"p1",value:"invalid-date"}},{sort:"newest",position:{productId:"p1",value:"2026-01-01T00:00:00Z"}},
    {sort:"retail-price-asc",retail:true,position:{productId:"p1",value:"-1",nullRank:0}},{sort:"retail-price-asc",retail:true,position:{productId:"p1",value:"1.5",nullRank:0}},{sort:"retail-price-desc",retail:true,position:{productId:"p1",value:"abc",nullRank:0}},{sort:"retail-price-desc",retail:true,position:{productId:"p1",value:"9007199254740992",nullRank:0}},{sort:"retail-price-asc",retail:true,position:{productId:"p1",value:"1",nullRank:1}},{sort:"retail-price-desc",retail:true,position:{productId:"p1",value:"1"}},
    {sort:"name-asc",position:{productId:"p1",value:"thinkpad",nullRank:0}},{sort:"name-desc",position:{productId:"p1",value:"ThinkPad"}},{sort:"name-asc",position:{productId:"p1",value:"x".repeat(513)}},{sort:"name-desc",position:{productId:" p1",value:"thinkpad"}},
  ];for(const testCase of cases){const repo=new MemoryRepository();const result=await new SearchCatalogProductsUseCase(repo).execute({context:actor(["catalog.products.view",...(testCase.retail?["pricing.view"]:[])]),input:{q:testCase.sort==="relevance"?"x":undefined,sort:testCase.sort,retailCurrency:testCase.retail?"USD":undefined,cursor:tamperedCursor(testCase.sort,testCase.position,testCase.retail)}});assert.deepEqual(result,{ok:false,error:"InvalidCursor"},`${testCase.sort}:${testCase.position.value}`);assert.equal(repo.invocations,0);}});
  it("does not project Branch availability or quantities without Branch context",async()=>{const result=await new SearchCatalogProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.products.view","inventory.quantity.view"]),input:{}});assert.ok(result.ok);if(result.ok){assert.equal("availability" in result.value.items[0]!,false);assert.equal("inventory" in result.value.items[0]!,false);}});
  it("keeps Owner inventory behavior fully authorized",async()=>{const result=await new GetCatalogProductDetailsUseCase(new MemoryRepository()).execute({context:actor([],"Owner"),productId:"p1",branchId:"branch-a"});assert.ok(result.ok);if(result.ok){assert.equal(result.value.availability,"InStock");assert.equal(result.value.inventory?.available,"7");}});
  it("returns scoped filter options and safe capabilities only through the repository boundary",async()=>{const repo=new MemoryRepository();const result=await new GetCatalogFilterOptionsUseCase(repo).execute({context:actor(["catalog.products.view","pricing.view","inventory.availability.view"])});assert.ok(result.ok);if(!result.ok)return;assert.deepEqual(repo.lastAllowedBranchIds,["branch-a"]);assert.deepEqual(result.value.capabilities.lifecycles,["Published"]);assert.deepEqual(result.value.capabilities.listingFilters,["Listed"]);assert.deepEqual(result.value.capabilities.stockFilters,["InStock","OutOfStock"]);assert.equal(result.value.capabilities.retailPrice,true);});
  it("derives independent direct-share modes only from trusted server authority",async()=>{for(const testCase of [{permissions:["catalog.products.view","catalog.sharing.create","pricing.view"],expected:["Retail"]},{permissions:["catalog.products.view","catalog.sharing.create","pricing.wholesale.view"],expected:["Wholesale"]},{permissions:["catalog.products.view","catalog.sharing.create","pricing.view","pricing.wholesale.view"],expected:["Retail","Wholesale"]},{permissions:["catalog.products.view","pricing.view","pricing.wholesale.view"],expected:[]}] as const){const result=await new GetCatalogProductDetailsUseCase(new MemoryRepository()).execute({context:actor(testCase.permissions),productId:"p1",branchId:"branch-a"});assert.ok(result.ok);if(result.ok)assert.deepEqual(result.value.capabilities.directSharePriceModes,testCase.expected);}});
  it("non-discloses unpublished or unlisted details from ordinary Catalog viewers",async()=>{const draftRepo=new MemoryRepository();draftRepo.details={...projection("p1"),lifecycle:"Draft"};assert.deepEqual(await new GetCatalogProductDetailsUseCase(draftRepo).execute({context:actor(["catalog.products.view"]),productId:"p1"}),{ok:false,error:"ProductNotFound"});const unlistedRepo=new MemoryRepository();unlistedRepo.details={...projection("p1"),listingStatus:"Unlisted"};assert.deepEqual(await new GetCatalogProductDetailsUseCase(unlistedRepo).execute({context:actor(["catalog.products.view"]),productId:"p1",branchId:"branch-a"}),{ok:false,error:"ProductNotFound"});const editor=await new GetCatalogProductDetailsUseCase(draftRepo).execute({context:actor(["catalog.products.view","catalog.products.edit"]),productId:"p1"});assert.ok(editor.ok);});
  it("downloads only authorized canonical WebP media and non-discloses failures",async()=>{const repo=new MemoryRepository();repo.media={productId:"p1",mediaId:"m",lifecycle:"Published",storageRootKey:"root",storageKey:"media/m.webp",checksumSha256:"a".repeat(64),mimeType:"image/webp"};let observed:Parameters<ProductMediaReaderPort["read"]>[0]|undefined;const reader:ProductMediaReaderPort={read:async(input)=>{observed=input;return {type:"Found",bytes:Uint8Array.from([82,73,70,70])}}};const useCase=new DownloadCatalogProductMediaUseCase(repo,reader);const result=await useCase.execute({context:actor(["catalog.products.view"]),productId:"p1",mediaId:"m"});assert.ok(result.ok);if(result.ok)assert.deepEqual([...result.value.bytes],[82,73,70,70]);assert.equal(observed?.maximumBytes,8*1024*1024);repo.media={...repo.media,lifecycle:"Draft"};assert.deepEqual(await useCase.execute({context:actor(["catalog.products.view"]),productId:"p1",mediaId:"m"}),{ok:false,error:"MediaUnavailable"});assert.deepEqual(await useCase.execute({context:actor(),productId:"p1",mediaId:"m"}),{ok:false,error:"Forbidden"});});
});

describe("Operational Product discovery application",()=>{
  const cases = [
    {purpose:"Listing",permission:"catalog.product.edit",branchId:"branch-a"},
    {purpose:"Listing",permission:"catalog.products.edit",branchId:"branch-a"},
    {purpose:"WorkspacePricing",permission:"pricing.manage"},
    {purpose:"BranchPricing",permission:"pricing.branchOverride.manage",branchId:"branch-a"},
    {purpose:"WorkspaceReferenceCost",permission:"referenceCost.manage"},
    {purpose:"BranchReferenceCost",permission:"referenceCost.branchOverride.manage",branchId:"branch-a"},
  ] as const;
  const negativeAuthorizationCases = [
    {purpose:"Listing",permission:"inventory.reserve",branchId:"branch-a"},
    {purpose:"Inventory",permission:"catalog.product.edit",branchId:"branch-a"},
    {purpose:"WorkspacePricing",permission:"pricing.branchOverride.manage"},
    {purpose:"BranchPricing",permission:"pricing.manage",branchId:"branch-a"},
    {purpose:"WorkspaceReferenceCost",permission:"referenceCost.branchOverride.manage"},
    {purpose:"BranchReferenceCost",permission:"referenceCost.manage",branchId:"branch-a"},
  ] as const;
  it("authorizes each exact purpose permission without requiring ordinary Catalog view",async()=>{for(const testCase of cases){const repo=new MemoryRepository();const result=await new SearchOperationalProductsUseCase(repo).execute({context:actor([testCase.permission]),input:{purpose:testCase.purpose,branchId:"branchId" in testCase?testCase.branchId:undefined}});assert.ok(result.ok,`${testCase.purpose}:${testCase.permission}`);assert.deepEqual(repo.lastSearch?.lifecycleScope,{type:"Allowed",lifecycles:["Draft","Published"]});assert.deepEqual(repo.lastSearch?.filters,{});}});
  it("accepts every relevant Inventory authority independently",async()=>{for(const permission of ["inventory.availability.view","inventory.quantity.view","inventory.receive","inventory.issue","inventory.reserve","inventory.transfer","inventory.damage","inventory.adjust"]){const result=await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:actor([permission]),input:{purpose:"Inventory",branchId:"branch-a"}});assert.ok(result.ok,permission);}});
  it("rejects unrelated authority for every operational discovery purpose",async()=>{for(const testCase of negativeAuthorizationCases){const repo=new MemoryRepository();const result=await new SearchOperationalProductsUseCase(repo).execute({context:actor([testCase.permission]),input:{purpose:testCase.purpose,branchId:"branchId" in testCase?testCase.branchId:undefined}});assert.deepEqual(result,{ok:false,error:"Forbidden"},`${testCase.purpose}:${testCase.permission}`);assert.equal(repo.invocations,0);}});
  it("enforces required/forbidden Branch context and hides out-of-scope Branches",async()=>{assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.product.edit"]),input:{purpose:"Listing"}}),{ok:false,error:"InvalidQuery"});assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:actor(["pricing.manage"]),input:{purpose:"WorkspacePricing",branchId:"branch-a"}}),{ok:false,error:"InvalidQuery"});assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.product.edit"]),input:{purpose:"Listing",branchId:"branch-b"}}),{ok:false,error:"BranchNotFound"});});
  it("returns BranchNotFound for a same-scope nonexistent Branch without searching",async()=>{const repo=new MemoryRepository();repo.branch=false;const result=await new SearchOperationalProductsUseCase(repo).execute({context:actor(["catalog.product.edit"]),input:{purpose:"Listing",branchId:"branch-a"}});assert.deepEqual(result,{ok:false,error:"BranchNotFound"});assert.equal(repo.invocations,1);assert.equal(repo.lastSearch,undefined);});
  it("returns only mixed-lifecycle identity and optional Branch/listing selection fields",async()=>{const repo=new MemoryRepository();repo.rows=[{product:{...projection("draft"),lifecycle:"Draft",listingStatus:"NotConfigured"},cursor:{productId:"draft",value:"1000"}},{product:{...projection("published"),lifecycle:"Published",listingStatus:"Unlisted"},cursor:{productId:"published",value:"900"}}];const branch=await new SearchOperationalProductsUseCase(repo).execute({context:actor(["catalog.product.edit"]),input:{purpose:"Listing",branchId:"branch-a"}});assert.ok(branch.ok);if(branch.ok){assert.deepEqual(branch.value.items.map((item)=>item.lifecycle),["Draft","Published"]);assert.deepEqual(Object.keys(branch.value.items[0]!).sort(),["branchId","lifecycle","listingStatus","productCode","productId","productName"]);assert.equal(JSON.stringify(branch.value).includes("workspaceId"),false);assert.equal(JSON.stringify(branch.value).includes("retail"),false);}const workspace=await new SearchOperationalProductsUseCase(repo).execute({context:actor(["pricing.manage"]),input:{purpose:"WorkspacePricing"}});assert.ok(workspace.ok);if(workspace.ok){assert.equal("branchId" in workspace.value.items[0]!,false);assert.equal("listingStatus" in workspace.value.items[0]!,false);}});
  it("binds operational cursors to purpose, Branch, query, and ordinary-vs-operational shape",async()=>{const repo=new MemoryRepository();const allBranches={...actor(["catalog.product.edit","inventory.reserve"]),branchScope:{type:"AllBranches" as const}};const first=await new SearchOperationalProductsUseCase(repo).execute({context:allBranches,input:{purpose:"Listing",branchId:"branch-a",q:"x",limit:1}});assert.ok(first.ok);if(!first.ok)return;const cursor=first.value.nextCursor!;assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:allBranches,input:{purpose:"Inventory",branchId:"branch-a",q:"x",cursor}}),{ok:false,error:"InvalidCursor"});assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:allBranches,input:{purpose:"Listing",branchId:"branch-b",q:"x",cursor}}),{ok:false,error:"InvalidCursor"});assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:allBranches,input:{purpose:"Listing",branchId:"branch-a",q:"changed",cursor}}),{ok:false,error:"InvalidCursor"});assert.deepEqual(await new SearchCatalogProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.products.view"]),input:{branchId:"branch-a",q:"x",cursor}}),{ok:false,error:"InvalidCursor"});const ordinary=await new SearchCatalogProductsUseCase(new MemoryRepository()).execute({context:actor(["catalog.products.view"]),input:{branchId:"branch-a",q:"x",limit:1}});assert.ok(ordinary.ok);if(ordinary.ok)assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:allBranches,input:{purpose:"Listing",branchId:"branch-a",q:"x",cursor:ordinary.value.nextCursor!}}),{ok:false,error:"InvalidCursor"});});
  it("enforces default/minimum/maximum limits",async()=>{const repo=new MemoryRepository();await new SearchOperationalProductsUseCase(repo).execute({context:actor(["pricing.manage"]),input:{purpose:"WorkspacePricing"}});assert.equal(repo.lastSearch?.limit,25);await new SearchOperationalProductsUseCase(repo).execute({context:actor(["pricing.manage"]),input:{purpose:"WorkspacePricing",limit:60}});assert.equal(repo.lastSearch?.limit,61);for(const limit of [0,61])assert.deepEqual(await new SearchOperationalProductsUseCase(new MemoryRepository()).execute({context:actor(["pricing.manage"]),input:{purpose:"WorkspacePricing",limit}}),{ok:false,error:"InvalidQuery"});});
});
