import { AuthenticatedContextUnavailableError, RestrictedSessionContextError, type TrustedActorContext } from "../../../../../shared/auth/trusted-actor-context";
import type { BranchProductResult } from "../../application/branch-product-results";
import type { BranchProductServerApplication } from "../branch-product-server-runtime";

type Open = () => BranchProductServerApplication; type Body = Record<string, unknown>;
const json = (value: unknown, status = 200) => Response.json(value, { status });
const response = <T>(result: BranchProductResult<T>) => result.ok ? json({ type: "Success", value: result.value }) : json({ type: result.error }, result.error === "Forbidden" ? 403 : result.error === "BranchNotFound" || result.error === "ProductNotFound" ? 404 : result.error === "Conflict" ? 409 : 400);
const bodyOf = async (request: Request): Promise<Body | null> => { try { const body = await request.json() as unknown; return body && typeof body === "object" && !Array.isArray(body) ? body as Body : null; } catch { return null; } };
const withApp = async (open: Open, request: Request, write: boolean, work: (app: BranchProductServerApplication, context: TrustedActorContext) => Promise<Response>) => { let app: BranchProductServerApplication | undefined; try { app = open(); if (write && !app.origin.allows(request)) return json({ type: "OriginNotAllowed" }, 403); return await work(app, await app.context.resolve(request)); } catch (error) { if (error instanceof AuthenticatedContextUnavailableError) return json({ type: "AuthenticationRequired" }, 401); if (error instanceof RestrictedSessionContextError) return json({ type: "ForbiddenForRestrictedSession" }, 403); return json({ type: "BranchProductServiceUnavailable" }, 503); } finally { try { await app?.close(); } catch {} } };

export const createBranchProductRouteHandlers = (open: Open) => ({
  getOperational: (request: Request, branchId: string, productId: string) => withApp(open, request, false, async (app, context) => response(await app.getOperational.execute({ context, branchId, productId }))),
  getListing: (request: Request, branchId: string, productId: string) => withApp(open, request, false, async (app, context) => response(await app.getListing.execute({ context, branchId, productId }))),
  setListing: (request: Request, branchId: string, productId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); return body && (body.listingStatus === "Listed" || body.listingStatus === "Unlisted") && typeof body.expectedRevision === "number" ? response(await app.setListing.execute({ context, branchId, productId, listingStatus: body.listingStatus, expectedRevision: body.expectedRevision })) : json({ type: "InvalidInput" }, 400); }),
  getPricing: (request: Request, branchId: string, productId: string) => withApp(open, request, false, async (app, context) => response(await app.getPricing.execute({ context, branchId, productId }))),
  setBasePrice: (request: Request, productId: string, priceType: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); return body && typeof body.amountMinor === "string" && typeof body.currency === "string" && typeof body.expectedRevision === "number" ? response(await app.setBasePrice.execute({ context, productId, priceType, amountMinor: body.amountMinor, currency: body.currency, expectedRevision: body.expectedRevision })) : json({ type: "InvalidInput" }, 400); }),
  clearBasePrice: (request: Request, productId: string, priceType: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); return body && typeof body.expectedRevision === "number" ? response(await app.clearBasePrice.execute({ context, productId, priceType, expectedRevision: body.expectedRevision })) : json({ type: "InvalidInput" }, 400); }),
  setOverride: (request: Request, branchId: string, productId: string, priceType: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); return body && typeof body.amountMinor === "string" && typeof body.currency === "string" && typeof body.expectedRevision === "number" ? response(await app.setOverride.execute({ context, branchId, productId, priceType, amountMinor: body.amountMinor, currency: body.currency, expectedRevision: body.expectedRevision })) : json({ type: "InvalidInput" }, 400); }),
  clearOverride: (request: Request, branchId: string, productId: string, priceType: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); return body && typeof body.expectedRevision === "number" ? response(await app.clearOverride.execute({ context, branchId, productId, priceType, expectedRevision: body.expectedRevision })) : json({ type: "InvalidInput" }, 400); }),
});
