import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { AuthenticatedContextUnavailableError, type TrustedActorContext } from "../../../../../shared/auth/trusted-actor-context";
import { createBranchProductRouteHandlers } from "./branch-product-route-handlers";
import type { BranchProductServerApplication } from "../branch-product-server-runtime";

const actor: TrustedActorContext = { workspaceId: "workspace-a", actorId: "actor-a", role: "Owner", permissions: [], branchScope: { type: "AllBranches" }, authorizationVersion: 1 };
const request = (body: unknown) => new Request("https://catalog.test/api", { method: "PUT", headers: { "content-type": "application/json", origin: "https://catalog.test" }, body: JSON.stringify(body) });
const open = (result: Readonly<Record<string, unknown>> = { ok: true, value: { priceType: "Retail" } }, resolve = async () => actor) => () => ({ context: { resolve }, origin: { allows: () => true }, getOperational: { execute: async () => result }, getListing: { execute: async () => result }, setListing: { execute: async () => result }, getPricing: { execute: async () => result }, setBasePrice: { execute: async () => result }, clearBasePrice: { execute: async () => result }, setOverride: { execute: async () => result }, clearOverride: { execute: async () => result }, close: async () => undefined }) as unknown as BranchProductServerApplication;

describe("Branch Product HTTP boundary", () => {
  it("requires server authentication and decimal-string Money", async () => { const unauthenticated = await createBranchProductRouteHandlers(open({}, async () => { throw new AuthenticatedContextUnavailableError(); })).setBasePrice(request({ amountMinor: "1", currency: "USD", expectedRevision: 0 }), "product-a", "Retail"); assert.equal(unauthenticated.status, 401); const malformed = await createBranchProductRouteHandlers(open()).setBasePrice(request({ amountMinor: 1, currency: "USD", expectedRevision: 0 }), "product-a", "Retail"); assert.equal(malformed.status, 400); });
  it("maps permission, tenant-safe not-found, optimistic conflict, and success", async () => { assert.equal((await createBranchProductRouteHandlers(open({ ok: false, error: "Forbidden" })).setOverride(request({ amountMinor: "1", currency: "USD", expectedRevision: 0 }), "branch-a", "product-a", "Retail")).status, 403); assert.equal((await createBranchProductRouteHandlers(open({ ok: false, error: "BranchNotFound" })).setOverride(request({ amountMinor: "1", currency: "USD", expectedRevision: 0 }), "branch-a", "product-a", "Retail")).status, 404); assert.equal((await createBranchProductRouteHandlers(open({ ok: false, error: "Conflict" })).setOverride(request({ amountMinor: "1", currency: "USD", expectedRevision: 0 }), "branch-a", "product-a", "Retail")).status, 409); assert.equal((await createBranchProductRouteHandlers(open()).setOverride(request({ amountMinor: "1", currency: "USD", expectedRevision: 0 }), "branch-a", "product-a", "Retail")).status, 200); });
  it("serves the Listing management-state read privately and rejects query input",async()=>{const handlers=createBranchProductRouteHandlers(open({ok:true,value:{branchId:"branch-a",productId:"product-a",listingStatus:"NotConfigured",revision:0,updatedAt:null,allowedActions:["SetListed","SetUnlisted"]}}));const response=await handlers.getListing(new Request("https://catalog.test/api/branches/branch-a/products/product-a/listing"),"branch-a","product-a");assert.equal(response.status,200);assert.equal(response.headers.get("cache-control"),"private, no-store");assert.equal((await handlers.getListing(new Request("https://catalog.test/api/branches/branch-a/products/product-a/listing?workspaceId=x"),"branch-a","product-a")).status,400);});
  it("maps Listing authentication, explicit permission failure, and scoped non-disclosure",async()=>{const read=new Request("https://catalog.test/api/branches/branch-a/products/product-a/listing");assert.equal((await createBranchProductRouteHandlers(open({},async()=>{throw new AuthenticatedContextUnavailableError()})).getListing(read,"branch-a","product-a")).status,401);assert.equal((await createBranchProductRouteHandlers(open({ok:false,error:"Forbidden"})).getListing(read,"branch-a","product-a")).status,403);assert.equal((await createBranchProductRouteHandlers(open({ok:false,error:"ProductNotFound"})).getListing(read,"branch-a","product-a")).status,404);});
});
