import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { TrustedActorContext } from "../../../../shared/auth/trusted-actor-context";
import type { BranchPriceOverride, PriceType, PriceValue } from "../domain/branch-product";
import type { BranchProductListingRepository, BranchProductTransactionContext, BranchProductUnitOfWork, ProductPricingRepository } from "../ports/branch-product-unit-of-work.port";
import { ClearBranchPriceOverrideUseCase, GetBranchProductListingUseCase, GetBranchProductPricingUseCase, SetBranchPriceOverrideUseCase, SetBranchProductListingUseCase, SetWorkspaceBasePriceUseCase } from "./branch-product.use-cases";

const actor = (permissions: readonly string[], branchIds?: readonly string[]): TrustedActorContext => ({ workspaceId: "workspace-a", actorId: "actor-a", role: "Staff", permissions, branchScope: branchIds ? { type: "SelectedBranches", branchIds } : { type: "AllBranches" }, authorizationVersion: 1 });
const pkey = (productId: string, type: PriceType) => `${productId}:${type}`; const okey = (branchId: string, productId: string, type: PriceType) => `${branchId}:${productId}:${type}`;
class MemoryPricing implements ProductPricingRepository {
  readonly base = new Map<string, PriceValue>(); readonly overrides = new Map<string, BranchPriceOverride>();
  getBase(_workspaceId: string, productId: string, priceType: PriceType) { return Promise.resolve(this.base.get(pkey(productId, priceType)) ?? null); }
  setBase(input: { workspaceId: string; productId: string; priceType: PriceType; amountMinor: bigint; currency: string; expectedRevision: number; now: Date }) { const key = pkey(input.productId, input.priceType); const current = this.base.get(key); if ((current?.revision ?? 0) !== input.expectedRevision) return Promise.resolve(null); const value = Object.freeze({ amountMinor: input.amountMinor, currency: input.currency, revision: input.expectedRevision + 1 }); this.base.set(key, value); return Promise.resolve(value); }
  clearBase() { return Promise.resolve(true); }
  getOverride(_workspaceId: string, branchId: string, productId: string, priceType: PriceType) { return Promise.resolve(this.overrides.get(okey(branchId, productId, priceType)) ?? null); }
  setOverride(input: { workspaceId: string; branchId: string; productId: string; priceType: PriceType; amountMinor: bigint; currency: string; expectedRevision: number; now: Date }) { const key = okey(input.branchId, input.productId, input.priceType); const current = this.overrides.get(key); if ((current?.revision ?? 0) !== input.expectedRevision) return Promise.resolve(null); const value = Object.freeze({ workspaceId: input.workspaceId, branchId: input.branchId, productId: input.productId, priceType: input.priceType, amountMinor: input.amountMinor, currency: input.currency, revision: input.expectedRevision + 1, createdAt: current?.createdAt ?? input.now, updatedAt: input.now }); this.overrides.set(key, value); return Promise.resolve(value); }
  clearOverride(input: { branchId: string; productId: string; priceType: PriceType; expectedRevision: number }) { const key = okey(input.branchId, input.productId, input.priceType); const current = this.overrides.get(key); if (!current || current.revision !== input.expectedRevision) return Promise.resolve(false); this.overrides.delete(key); return Promise.resolve(true); }
}
class MemoryListings implements BranchProductListingRepository { value: Awaited<ReturnType<BranchProductListingRepository["get"]>> = null; get() { return Promise.resolve(this.value); } set(input: Parameters<BranchProductListingRepository["set"]>[0]) { if ((this.value?.revision ?? 0) !== input.expectedRevision) return Promise.resolve(null); this.value = { status: input.status, revision: input.expectedRevision + 1, createdAt: this.value?.createdAt ?? input.now, updatedAt: input.now }; return Promise.resolve(this.value); } }
const fixture = () => { const pricing = new MemoryPricing(); const listings = new MemoryListings(); const transaction: BranchProductTransactionContext = { scope: { findBranch: async (_workspaceId, branchId) => branchId === "foreign" ? null : { status: "Active" }, findProduct: async (_workspaceId, productId) => productId === "missing" ? null : { lifecycleState: productId === "archived" ? "Archived" : "Published", revision: 0 }, isCurrencyEnabled: async (_workspaceId, currency) => currency === "USD" }, pricing, listings, inventory: { getBalance: async () => null }, audit: { append: async () => undefined } }; const unitOfWork: BranchProductUnitOfWork = { execute: (work) => work(transaction) }; const dependencies = { unitOfWork, clock: { now: () => new Date("2026-08-20T10:00:00Z") } }; return { pricing, listings, get: new GetBranchProductPricingUseCase(unitOfWork), getListing: new GetBranchProductListingUseCase(unitOfWork), setListing: new SetBranchProductListingUseCase(dependencies), setBase: new SetWorkspaceBasePriceUseCase(dependencies), setOverride: new SetBranchPriceOverrideUseCase(dependencies), clearOverride: new ClearBranchPriceOverrideUseCase(dependencies) }; };

describe("Branch pricing", () => {
  it("inherits live Workspace Retail and keeps an explicit Branch override across base changes", async () => { const app = fixture(); const manager = actor(["pricing.view", "pricing.manage", "pricing.branchOverride.manage"]); assert.ok((await app.setBase.execute({ context: manager, productId: "product-a", priceType: "Retail", amountMinor: "1000", currency: "USD", expectedRevision: 0 })).ok); let read = await app.get.execute({ context: manager, branchId: "branch-a", productId: "product-a" }); assert.ok(read.ok); assert.equal(((read.ok ? read.value.prices : {}) as Record<string, { effective: { amountMinor: string } }>).Retail.effective.amountMinor, "1000"); assert.ok((await app.setOverride.execute({ context: manager, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "900", currency: "USD", expectedRevision: 0 })).ok); assert.ok((await app.setBase.execute({ context: manager, productId: "product-a", priceType: "Retail", amountMinor: "1100", currency: "USD", expectedRevision: 1 })).ok); read = await app.get.execute({ context: manager, branchId: "branch-a", productId: "product-a" }); assert.equal(((read.ok ? read.value.prices : {}) as Record<string, { effective: { amountMinor: string } }>).Retail.effective.amountMinor, "900"); });
  it("treats zero as a price and clearing as a distinct operation", async () => { const app = fixture(); const manager = actor(["pricing.view", "pricing.branchOverride.manage"]); const set = await app.setOverride.execute({ context: manager, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "0", currency: "USD", expectedRevision: 0 }); assert.ok(set.ok); assert.ok((await app.clearOverride.execute({ context: manager, branchId: "branch-a", productId: "product-a", priceType: "Retail", expectedRevision: 1 })).ok); assert.equal(app.pricing.overrides.size, 0); });
  it("hides Wholesale and Reference Cost without their dedicated view permissions", async () => { const app = fixture(); app.pricing.base.set(pkey("product-a", "Wholesale"), { amountMinor: BigInt(800), currency: "USD", revision: 1 }); app.pricing.base.set(pkey("product-a", "ReferenceCost"), { amountMinor: BigInt(700), currency: "USD", revision: 1 }); const read = await app.get.execute({ context: actor(["pricing.view"]), branchId: "branch-a", productId: "product-a" }); assert.ok(read.ok); const prices = (read.ok ? read.value.prices : {}) as Record<string, unknown>; assert.deepEqual(Object.keys(prices), ["Retail"]); });
  it("rejects disabled currency and out-of-scope Branch override without disclosure", async () => { const app = fixture(); const manager = actor(["pricing.branchOverride.manage"], ["branch-a"]); assert.deepEqual(await app.setOverride.execute({ context: manager, branchId: "branch-b", productId: "product-a", priceType: "Retail", amountMinor: "1", currency: "USD", expectedRevision: 0 }), { ok: false, error: "BranchNotFound" }); assert.deepEqual(await app.setOverride.execute({ context: manager, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "1", currency: "EUR", expectedRevision: 0 }), { ok: false, error: "CurrencyNotAllowed" }); });
});

describe("Branch Product listing", () => {
  it("treats absence as NotConfigured and persists explicit list/unlist state", async () => { const app = fixture(); const editor = actor(["catalog.products.view", "catalog.products.edit"]); const absent = await app.getListing.execute({ context: editor, branchId: "branch-a", productId: "product-a" }); assert.ok(absent.ok); assert.equal(absent.ok ? absent.value.listingStatus : null, "NotConfigured"); assert.ok((await app.setListing.execute({ context: editor, branchId: "branch-a", productId: "product-a", listingStatus: "Listed", expectedRevision: 0 })).ok); const unlisted = await app.setListing.execute({ context: editor, branchId: "branch-a", productId: "product-a", listingStatus: "Unlisted", expectedRevision: 1 }); assert.ok(unlisted.ok); assert.equal(unlisted.ok ? unlisted.value.listingStatus : null, "Unlisted"); });
  it("rejects archived Product listing and out-of-scope Branch", async () => { const app = fixture(); const editor = actor(["catalog.products.edit"], ["branch-a"]); assert.deepEqual(await app.setListing.execute({ context: editor, branchId: "branch-b", productId: "product-a", listingStatus: "Listed", expectedRevision: 0 }), { ok: false, error: "Forbidden" }); assert.deepEqual(await app.setListing.execute({ context: editor, branchId: "branch-a", productId: "archived", listingStatus: "Listed", expectedRevision: 0 }), { ok: false, error: "ProductArchived" }); });
});
