import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { OperationalManagementCapabilitiesClient } from "../../../identity/presentation/operational-management-capabilities.client";
import { operationalManagementCapabilitiesFixture } from "../../../identity/presentation/mock/operational-management-capabilities.fixture";
import { OperationalProductApiClient } from "../../../catalog/query/presentation/operational-product-api.client";
import { OperationalProductSelectorCoordinator, operationalProductSelection } from "../../../catalog/query/presentation/operational-product-selector.coordinator";
import { operationalProductRequestKey } from "../../../catalog/query/presentation/operational-product-query-state";
import { operationalProductPageFixture } from "../../../catalog/query/presentation/mock/operational-product.fixture";
import { ListingApiClient, type FetchPort } from "../../../catalog/branch-products/presentation/listing-api.client";
import { ListingCoordinator } from "../../../catalog/branch-products/presentation/listing.coordinator";
import { listingFixture, listingWriteFixture } from "../../../catalog/branch-products/presentation/mock/listing.fixture";
import { OperationalBranchApiClient } from "./operational-branch-api.client";
import { OperationalBranchSelectorCoordinator } from "./operational-branch-selector.coordinator";
import { operationalBranchFixture } from "./mock/operational-branch.fixture";
import { operationsProductDiscovery } from "./operations-product-context";
import { resolveOperationsQuery } from "./operations-query-state";
import { listingSelectionKey, operationsListingResource } from "./operations-listing-context";
import type { OperationalBranchState } from "./operational-branch-selector.types";
const callbacks = { onChange() {}, onAuthenticationRequired() { assert.fail("Unexpected expiry"); } };
const success = (value: unknown) => Response.json({ type: "Success", value });
const capabilities = () => { const result = operationalManagementCapabilitiesFixture(); result.listing.canManage = true; return result; };
describe("P2 Operations Listing integration", () => {
  it("composes A1 → A6 → A2 → GET → explicit PUT → authoritative GET with conflict review", async () => {
    const calls: string[] = [], revisions: number[] = []; let reads = 0;
    const products = operationalProductPageFixture("branch-main"), product = products.items[0];
    const fetchPort: FetchPort = async (input, init) => {
      const url = String(input); calls.push(`${init?.method} ${url}`);
      if (url === "/api/operations/capabilities") return Response.json(capabilities());
      if (url === "/api/branches/operational?purpose=Listing") return success([operationalBranchFixture()]);
      if (url === "/api/catalog/operational-products?purpose=Listing&branchId=branch-main") return success(products);
      assert.equal(url, `/api/branches/branch-main/products/${product.productId}/listing`);
      if (init?.method === "GET") return success(listingFixture({ productId: product.productId, revision: ++reads + 1 }));
      assert.equal(init?.method, "PUT"); const body = JSON.parse(String(init.body)); assert.equal(body.listingStatus, "Unlisted"); revisions.push(body.expectedRevision);
      return revisions.length === 1 ? Response.json({ type: "Conflict" }, { status: 409 }) : success(listingWriteFixture({ productId: product.productId }));
    };
    const a1 = await new OperationalManagementCapabilitiesClient(fetchPort).load(); assert.equal(a1.ok, true);
    const query = resolveOperationsQuery(new URLSearchParams(`section=branches&branchTool=listing&branchId=branch-main&productId=${product.productId}`), capabilities());
    assert.ok(query.context); const a6 = new OperationalBranchSelectorCoordinator(new OperationalBranchApiClient(fetchPort), callbacks); await a6.load("Listing");
    const discovery = operationsProductDiscovery(query.context, query.branchId, a6.snapshot); assert.equal(discovery.type, "Ready"); if (discovery.type !== "Ready") return;
    const request = { ...discovery.scope, q: "" }; const a2 = new OperationalProductSelectorCoordinator(new OperationalProductApiClient(fetchPort), callbacks); await a2.load(request);
    const selection = operationalProductSelection(a2.snapshot, operationalProductRequestKey(request), product.productId); assert.equal(selection.type, "Selected"); if (selection.type !== "Selected") return;
    const lifecycle = {}, known = { lifecycle, key: listingSelectionKey(query.context, query.branchId, query.products), product: selection.product };
    const target = operationsListingResource(query.context, query.branchId, query.products, a6.snapshot, lifecycle, known); assert.ok(target);
    const listing = new ListingCoordinator(new ListingApiClient(fetchPort), target.resource, callbacks); await listing.load();
    assert.equal(calls.length, 4); assert.deepEqual(revisions, []); listing.choose("SetUnlisted"); await listing.submit();
    await listing.submit(); assert.deepEqual(revisions, [2]); listing.reviewLatest(); await listing.submit(); assert.deepEqual(revisions, [2, 3]);
    assert.equal(reads, 3); assert.equal(listing.snapshot.saved, true);
    assert.equal(calls.some(call => call === "GET /api/branches"), false); listing.dispose(); a2.dispose(); a6.dispose();
  });
  it("preserves known inactive inspection, blocks fresh A2 and refuses writes even with an old action", async () => {
    const product = operationalProductPageFixture("branch-main").items[0], lifecycle = {};
    const q = resolveOperationsQuery(new URLSearchParams(`section=branches&branchTool=listing&branchId=branch-main&productId=${product.productId}`), capabilities()); assert.ok(q.context);
    const known = { lifecycle, key: listingSelectionKey(q.context, q.branchId, q.products), product };
    const branches: OperationalBranchState = { type: "Ready", purpose: "Listing", availability: "AllInactive", options: [operationalBranchFixture({ status: "Inactive" })] };
    assert.deepEqual(operationsProductDiscovery(q.context, q.branchId, branches), { type: "Waiting", reason: "InactiveBranch" });
    assert.equal(operationsListingResource(q.context, q.branchId, q.products, branches, lifecycle, null), null);
    const target = operationsListingResource(q.context, q.branchId, q.products, branches, lifecycle, known); assert.ok(target); assert.equal(target.inspectionOnly, true);
    const calls: string[] = [];
    const c = new ListingCoordinator(new ListingApiClient(async (url, init) => { calls.push(`${init?.method} ${url}`); assert.equal(init?.method, "GET"); return success(listingFixture({ productId: product.productId, allowedActions: [] })); }), target.resource, callbacks, target.inspectionOnly);
    await c.load(); c.choose("SetListed"); await c.submit(); assert.equal(calls.length, 1); assert.equal(c.snapshot.detail.type, "Ready"); c.dispose();
  });
  it("masks resources on actor, Branch, Product, search/page, purpose or A6 failure changes", () => {
    const product = operationalProductPageFixture("branch-main").items[0], lifecycle = {};
    const q = resolveOperationsQuery(new URLSearchParams(`section=branches&branchTool=listing&branchId=branch-main&productId=${product.productId}`), capabilities()); assert.ok(q.context);
    const branches: OperationalBranchState = { type: "Ready", purpose: "Listing", availability: "Available", options: [operationalBranchFixture()] };
    const known = { lifecycle, key: listingSelectionKey(q.context, q.branchId, q.products), product };
    const resolve = (patch: Parameters<typeof operationsListingResource>[2], actor = lifecycle, state: OperationalBranchState = branches) => operationsListingResource(q.context!, q.branchId, patch, state, actor, known);
    assert.ok(resolve(q.products)); assert.equal(resolve(q.products, {}), null);
    for (const patch of [{ productId: null }, { productId: "different" }, { q: "changed" }, { productCursor: "other" }]) assert.equal(resolve({ ...q.products, ...patch }), null);
    assert.equal(operationsListingResource(q.context, "another", q.products, branches, lifecycle, known), null);
    assert.equal(operationsListingResource({ section: "Inventory", inventoryTool: "stock" }, q.branchId, q.products, branches, lifecycle, known), null);
    for (const state of [{ type: "Loading", purpose: "Listing" }, { type: "Failed", purpose: "Listing", kind: "Forbidden" }, { ...branches, purpose: "Inventory" }, { ...branches, options: [] }] as OperationalBranchState[]) assert.equal(resolve(q.products, lifecycle, state), null);
  });
});
