import { AuthenticatedContextUnavailableError, RestrictedSessionContextError, type TrustedActorContext } from "../../../../shared/auth/trusted-actor-context";
import type { InventoryResult } from "../../application/inventory-results";
import type { InventoryServerApplication } from "../inventory-server-runtime";

type Open = () => InventoryServerApplication; type Body = Record<string, unknown>;
const json = (value: unknown, status = 200, privateCache = false) => Response.json(value, { status, ...(privateCache ? { headers: { "cache-control": "private, no-store" } } : {}) });
const response = <T>(result: InventoryResult<T>, created = false, privateCache = false) => { if (result.ok) return json({ type: "Success", value: result.value }, created ? 201 : 200, privateCache); const status = result.error === "Forbidden" ? 403 : result.error === "BranchNotFound" || result.error === "ProductNotFound" || result.error === "ReservationNotFound" ? 404 : result.error === "InventoryConflict" || result.error === "IdempotencyConflict" ? 409 : 400; return json({ type: result.error }, status, privateCache); };
const bodyOf = async (request: Request): Promise<Body | null> => { try { const value = await request.json() as unknown; return value && typeof value === "object" && !Array.isArray(value) ? value as Body : null; } catch { return null; } };
const text = (body: Body, key: string) => typeof body[key] === "string" ? body[key] as string : undefined;
const withApp = async (open: Open, request: Request, write: boolean, work: (app: InventoryServerApplication, context: TrustedActorContext) => Promise<Response>, privateCache = false) => { let app: InventoryServerApplication | undefined; try { app = open(); if (write && !app.origin.allows(request)) return json({ type: "OriginNotAllowed" }, 403, privateCache); return await work(app, await app.context.resolve(request)); } catch (error) { if (error instanceof AuthenticatedContextUnavailableError) return json({ type: "AuthenticationRequired" }, 401, privateCache); if (error instanceof RestrictedSessionContextError) return json({ type: "ForbiddenForRestrictedSession" }, 403, privateCache); return json({ type: "InventoryServiceUnavailable" }, 503, privateCache); } finally { try { await app?.close(); } catch {} } };
const quantityCommand = (context: TrustedActorContext, branchId: string, body: Body) => { const operationId = text(body, "operationId"); const productId = text(body, "productId"); const quantity = text(body, "quantity"); return operationId && productId && quantity ? { context, branchId, operationId, productId, quantity, ...(text(body, "reasonCode") ? { reasonCode: text(body, "reasonCode") } : {}), ...(text(body, "note") ? { note: text(body, "note") } : {}) } : null; };
const reservationCollectionQuery = (request: Request) => { const parameters = new URL(request.url).searchParams; const allowed = new Set(["productId", "cursor", "limit"]); if ([...parameters.keys()].some((key) => !allowed.has(key)) || [...allowed].some((key) => parameters.getAll(key).length > 1) || !parameters.has("productId")) return null; const productId = parameters.get("productId")!; const cursor = parameters.get("cursor") ?? undefined; const rawLimit = parameters.get("limit"); if (rawLimit !== null && !/^[1-9][0-9]*$/u.test(rawLimit)) return null; return { productId, ...(cursor !== undefined ? { cursor } : {}), ...(rawLimit !== null ? { limit: Number(rawLimit) } : {}) }; };

export const createInventoryRouteHandlers = (open: Open) => ({
  receive: (request: Request, branchId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const command = body && quantityCommand(context, branchId, body); return command ? response(await app.receive.execute(command)) : json({ type: "InvalidInput" }, 400); }),
  issue: (request: Request, branchId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const command = body && quantityCommand(context, branchId, body); return command ? response(await app.issue.execute(command)) : json({ type: "InvalidInput" }, 400); }),
  damage: (request: Request, branchId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const command = body && quantityCommand(context, branchId, body); return command ? response(await app.damage.execute(command)) : json({ type: "InvalidInput" }, 400); }),
  restore: (request: Request, branchId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const command = body && quantityCommand(context, branchId, body); return command ? response(await app.restore.execute(command)) : json({ type: "InvalidInput" }, 400); }),
  correct: (request: Request, branchId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const command = body && quantityCommand(context, branchId, body); const direction = body && text(body, "direction"); return command && (direction === "Increase" || direction === "Decrease") && command.reasonCode ? response(await app.correct.execute({ ...command, direction, reasonCode: command.reasonCode })) : json({ type: "InvalidInput" }, 400); }),
  reserve: (request: Request, branchId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const command = body && quantityCommand(context, branchId, body); return command ? response(await app.reserve.execute(command), true) : json({ type: "InvalidInput" }, 400); }),
  release: (request: Request, branchId: string, reservationId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const operationId = body && text(body, "operationId"); const quantity = body && text(body, "quantity"); return operationId && quantity ? response(await app.release.execute({ context, branchId, reservationId, operationId, quantity })) : json({ type: "InvalidInput" }, 400); }),
  fulfill: (request: Request, branchId: string, reservationId: string) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const operationId = body && text(body, "operationId"); const quantity = body && text(body, "quantity"); return operationId && quantity ? response(await app.fulfill.execute({ context, branchId, reservationId, operationId, quantity })) : json({ type: "InvalidInput" }, 400); }),
  transfer: (request: Request) => withApp(open, request, true, async (app, context) => { const body = await bodyOf(request); const operationId = body && text(body, "operationId"); const sourceBranchId = body && text(body, "sourceBranchId"); const destinationBranchId = body && text(body, "destinationBranchId"); const productId = body && text(body, "productId"); const quantity = body && text(body, "quantity"); return operationId && sourceBranchId && destinationBranchId && productId && quantity ? response(await app.transfer.execute({ context, operationId, sourceBranchId, destinationBranchId, productId, quantity, ...(text(body!, "reasonCode") ? { reasonCode: text(body!, "reasonCode") } : {}) })) : json({ type: "InvalidInput" }, 400); }),
  get: (request: Request, branchId: string, productId: string) => withApp(open, request, false, async (app, context) => response(await app.get.execute({ context, branchId, productId }))),
  movements: (request: Request, branchId: string, productId: string) => withApp(open, request, false, async (app, context) => { const raw = new URL(request.url).searchParams.get("limit"); return response(await app.movements.execute({ context, branchId, productId, ...(raw ? { limit: Number(raw) } : {}) })); }),
  reservations: (request: Request, branchId: string) => withApp(open, request, false, async (app, context) => { const query = reservationCollectionQuery(request); return query ? response(await app.reservations.execute({ context, branchId, ...query }), false, true) : json({ type: "InvalidInput" }, 400, true); }, true),
  reservation: (request: Request, branchId: string, reservationId: string) => withApp(open, request, false, async (app, context) => new URL(request.url).searchParams.size === 0 ? response(await app.reservation.execute({ context, branchId, reservationId }), false, true) : json({ type: "InvalidInput" }, 400, true), true),
});
