import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { after, before, beforeEach, describe, it } from "node:test";
import { and, eq, sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type { TrustedActorContext } from "../../../../shared/auth/trusted-actor-context";
import { createPlatformDatabaseConnection } from "../../../../shared/infrastructure/persistence/database";
import { catalogProductBranchPriceOverrides, catalogProducts, workspaceCurrencyAvailability } from "../../../catalog/infrastructure/persistence/schema";
import { ClearBranchPriceOverrideUseCase, GetBranchProductPricingUseCase, SetBranchPriceOverrideUseCase, SetWorkspaceBasePriceUseCase } from "../../../catalog/branch-products/application/branch-product.use-cases";
import { PostgreSqlBranchProductUnitOfWork } from "../../../catalog/branch-products/infrastructure/persistence/postgresql-branch-product-unit-of-work";
import { assertSafeIntegrationTestDatabaseUrl } from "../../../catalog/infrastructure/persistence/integration-test-database-safety";
import { workspaceBranchReferences, workspaces } from "../../../workspace/infrastructure/persistence/schema";
import { IssueInventoryUseCase, ReceiveInventoryUseCase, ReserveInventoryUseCase, TransferInventoryUseCase } from "../../application/inventory.use-cases";
import { inventoryBalances, inventoryMovements, inventoryOperations } from "./schema";
import { PostgreSqlInventoryUnitOfWork } from "./postgresql-inventory-unit-of-work";

const connectionUrl = process.env.TEST_DATABASE_URL; assertSafeIntegrationTestDatabaseUrl(connectionUrl, process.env.DATABASE_URL); const connection = createPlatformDatabaseConnection(connectionUrl!);
const inventoryUnitOfWork = new PostgreSqlInventoryUnitOfWork(connection.database); const inventoryDependencies = { unitOfWork: inventoryUnitOfWork, clock: { now: () => new Date() }, identifiers: { next: randomUUID }, fingerprint: { create: (value: Readonly<Record<string, string>>) => createHash("sha256").update(JSON.stringify(value)).digest("hex") } };
const receive = new ReceiveInventoryUseCase(inventoryDependencies); const issue = new IssueInventoryUseCase(inventoryDependencies); const reserve = new ReserveInventoryUseCase(inventoryDependencies); const transfer = new TransferInventoryUseCase(inventoryDependencies);
const pricingUnitOfWork = new PostgreSqlBranchProductUnitOfWork(connection.database); const pricingDependencies = { unitOfWork: pricingUnitOfWork, clock: { now: () => new Date() } }; const setBase = new SetWorkspaceBasePriceUseCase(pricingDependencies); const setOverride = new SetBranchPriceOverrideUseCase(pricingDependencies); const clearOverride = new ClearBranchPriceOverrideUseCase(pricingDependencies); const getPricing = new GetBranchProductPricingUseCase(pricingUnitOfWork);
const owner = (workspaceId = "workspace-a"): TrustedActorContext => ({ workspaceId, actorId: `owner-${workspaceId}`, role: "Owner", permissions: [], branchScope: { type: "AllBranches" }, authorizationVersion: 1 });

before(async () => migrate(connection.database, { migrationsFolder: "drizzle" }));
beforeEach(async () => { await connection.database.execute(sql`TRUNCATE TABLE catalog_products CASCADE`); await connection.database.execute(sql`TRUNCATE TABLE workspaces CASCADE`); const now = new Date(); await connection.database.insert(workspaces).values([{ workspaceId: "workspace-a", companyId: "company-a", workspaceCode: "workspace-a", displayName: "A", passwordRecoveryPolicy: "OwnerManagedOnly", createdAt: now, updatedAt: now }, { workspaceId: "workspace-b", companyId: "company-b", workspaceCode: "workspace-b", displayName: "B", passwordRecoveryPolicy: "OwnerManagedOnly", createdAt: now, updatedAt: now }]); await connection.database.insert(workspaceBranchReferences).values([{ workspaceId: "workspace-a", branchId: "branch-a", code: "branch-a", displayName: "A", status: "Active", sortOrder: 0, revision: 1, createdAt: now, updatedAt: now }, { workspaceId: "workspace-a", branchId: "branch-b", code: "branch-b", displayName: "B", status: "Active", sortOrder: 1, revision: 1, createdAt: now, updatedAt: now }, { workspaceId: "workspace-b", branchId: "branch-foreign", code: "branch-foreign", displayName: "Foreign", status: "Active", sortOrder: 0, revision: 1, createdAt: now, updatedAt: now }]); await connection.database.insert(catalogProducts).values([{ workspaceId: "workspace-a", productId: "product-a", catalogId: "catalog-a", lifecycleState: "Published", archiveReason: null, revision: 0, createdAt: now, updatedAt: now, hasClassification: false, hasCommercialDetails: false, isHighlighted: false }, { workspaceId: "workspace-b", productId: "product-foreign", catalogId: "catalog-b", lifecycleState: "Published", archiveReason: null, revision: 0, createdAt: now, updatedAt: now, hasClassification: false, hasCommercialDetails: false, isHighlighted: false }]); await connection.database.insert(workspaceCurrencyAvailability).values({ workspaceId: "workspace-a", currencyCode: "USD", enabled: true, sortOrder: 0 }); });
after(async () => connection.close());

describe("PostgreSQL Inventory concurrency and integrity", () => {
  it("serializes concurrent issue of the last piece", async () => { assert.ok((await receive.execute({ context: owner(), branchId: "branch-a", productId: "product-a", quantity: "1", operationId: "receive-concurrent-001" })).ok); const outcomes = await Promise.all(["issue-concurrent-001", "issue-concurrent-002"].map((operationId) => issue.execute({ context: owner(), branchId: "branch-a", productId: "product-a", quantity: "1", operationId }))); assert.equal(outcomes.filter((value) => value.ok).length, 1); assert.equal(outcomes.filter((value) => !value.ok && value.error === "InsufficientAvailableStock").length, 1); const rows = await connection.database.select().from(inventoryBalances); assert.equal(rows[0]?.onHandQuantity, BigInt(0)); });
  it("serializes concurrent reservations without oversubscription", async () => { await receive.execute({ context: owner(), branchId: "branch-a", productId: "product-a", quantity: "1", operationId: "receive-reserve-001" }); const outcomes = await Promise.all(["reserve-concurrent-001", "reserve-concurrent-002"].map((operationId) => reserve.execute({ context: owner(), branchId: "branch-a", productId: "product-a", quantity: "1", operationId }))); assert.equal(outcomes.filter((value) => value.ok).length, 1); assert.equal(outcomes.filter((value) => !value.ok && value.error === "InsufficientAvailableStock").length, 1); const [row] = await connection.database.select().from(inventoryBalances); assert.equal(row?.reservedQuantity, BigInt(1)); });
  it("keeps transfer atomic, idempotent, correlated, and tenant-safe", async () => { await receive.execute({ context: owner(), branchId: "branch-a", productId: "product-a", quantity: "3", operationId: "receive-transfer-001" }); const command = { context: owner(), sourceBranchId: "branch-a", destinationBranchId: "branch-b", productId: "product-a", quantity: "2", operationId: "transfer-atomic-001" }; const first = await transfer.execute(command); const retry = await transfer.execute(command); assert.ok(first.ok && retry.ok); const balances = await connection.database.select().from(inventoryBalances); assert.equal(balances.find((value) => value.branchId === "branch-a")?.onHandQuantity, BigInt(1)); assert.equal(balances.find((value) => value.branchId === "branch-b")?.onHandQuantity, BigInt(2)); assert.equal((await connection.database.select().from(inventoryMovements).where(eq(inventoryMovements.operationId, command.operationId))).length, 2); assert.equal((await connection.database.select().from(inventoryOperations).where(eq(inventoryOperations.operationId, command.operationId))).length, 1); const failed = await transfer.execute({ ...command, quantity: "9", operationId: "transfer-atomic-002" }); assert.equal(failed.ok, false); const unchanged = await connection.database.select().from(inventoryBalances); assert.equal(unchanged.find((value) => value.branchId === "branch-b")?.onHandQuantity, BigInt(2)); await assert.rejects(connection.database.insert(inventoryBalances).values({ workspaceId: "workspace-a", branchId: "branch-a", productId: "product-foreign", updatedAt: new Date() })); });
});

describe("PostgreSQL Branch pricing", () => {
  it("persists BIGINT Money, live inheritance, override, and explicit clear", async () => { const actor = owner(); assert.ok((await setBase.execute({ context: actor, productId: "product-a", priceType: "Retail", amountMinor: "9007199254740991", currency: "USD", expectedRevision: 0 })).ok); let read = await getPricing.execute({ context: actor, branchId: "branch-a", productId: "product-a" }); assert.ok(read.ok); const inherited = (read.ok ? read.value.prices : {}) as Record<string, { effective: { amountMinor: string }; source: string }>; assert.equal(inherited.Retail.effective.amountMinor, "9007199254740991"); assert.equal(inherited.Retail.source, "WorkspaceBase"); assert.ok((await setOverride.execute({ context: actor, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "0", currency: "USD", expectedRevision: 0 })).ok); assert.ok((await setBase.execute({ context: actor, productId: "product-a", priceType: "Retail", amountMinor: "100", currency: "USD", expectedRevision: 1 })).ok); read = await getPricing.execute({ context: actor, branchId: "branch-a", productId: "product-a" }); assert.equal(((read.ok ? read.value.prices : {}) as Record<string, { effective: { amountMinor: string } }>).Retail.effective.amountMinor, "0"); assert.ok((await clearOverride.execute({ context: actor, branchId: "branch-a", productId: "product-a", priceType: "Retail", expectedRevision: 1 })).ok); read = await getPricing.execute({ context: actor, branchId: "branch-a", productId: "product-a" }); assert.equal(((read.ok ? read.value.prices : {}) as Record<string, { effective: { amountMinor: string } }>).Retail.effective.amountMinor, "100"); assert.equal((await connection.database.select().from(catalogProductBranchPriceOverrides)).length, 0); });
  it("enforces scoped override uniqueness and enabled currency", async () => { const actor = owner(); assert.deepEqual(await setOverride.execute({ context: actor, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "1", currency: "EUR", expectedRevision: 0 }), { ok: false, error: "CurrencyNotAllowed" }); assert.ok((await setOverride.execute({ context: actor, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "1", currency: "USD", expectedRevision: 0 })).ok); assert.deepEqual(await setOverride.execute({ context: actor, branchId: "branch-a", productId: "product-a", priceType: "Retail", amountMinor: "2", currency: "USD", expectedRevision: 0 }), { ok: false, error: "Conflict" }); const rows = await connection.database.select().from(catalogProductBranchPriceOverrides).where(and(eq(catalogProductBranchPriceOverrides.workspaceId, "workspace-a"), eq(catalogProductBranchPriceOverrides.branchId, "branch-a"))); assert.equal(rows.length, 1); });
});
