import { randomUUID } from "node:crypto";
import { and, desc, eq } from "drizzle-orm";
import type { PlatformDatabase } from "../../../../shared/infrastructure/persistence/database";
import { securityAuditEvents } from "../../../../shared/audit/infrastructure/persistence/schema";
import { catalogProducts } from "../../../catalog/infrastructure/persistence/schema";
import { workspaceBranchReferences } from "../../../workspace/infrastructure/persistence/schema";
import type { InventoryBalance, InventoryMovement, InventoryMovementType, InventoryReservation, InventoryReservationStatus } from "../../domain/inventory";
import type { InventoryAuditRepository, InventoryRepository, InventoryScopeRepository, InventoryTransactionContext, InventoryUnitOfWork } from "../../ports/inventory-unit-of-work.port";
import { inventoryBalances, inventoryMovements, inventoryOperations, inventoryReservations } from "./schema";

const balance = (row: typeof inventoryBalances.$inferSelect): InventoryBalance => Object.freeze({ workspaceId: row.workspaceId, branchId: row.branchId, productId: row.productId, onHand: row.onHandQuantity, reserved: row.reservedQuantity, damaged: row.damagedQuantity, revision: row.revision, updatedAt: row.updatedAt });
const reservation = (row: typeof inventoryReservations.$inferSelect): InventoryReservation => Object.freeze({ workspaceId: row.workspaceId, reservationId: row.reservationId, branchId: row.branchId, productId: row.productId, quantity: row.quantity, remainingQuantity: row.remainingQuantity, status: row.status as InventoryReservationStatus, createdByActorId: row.createdByActorId, createdAt: row.createdAt, updatedAt: row.updatedAt });
const movement = (row: typeof inventoryMovements.$inferSelect): InventoryMovement => Object.freeze({ workspaceId: row.workspaceId, branchId: row.branchId, movementId: row.movementId, productId: row.productId, movementType: row.movementType as InventoryMovementType, quantity: row.quantity, occurredAt: row.occurredAt, createdAt: row.createdAt, createdByActorId: row.createdByActorId, operationId: row.operationId, ...(row.reservationId ? { reservationId: row.reservationId } : {}), ...(row.correlationId ? { correlationId: row.correlationId } : {}), ...(row.reasonCode ? { reasonCode: row.reasonCode } : {}), ...(row.note ? { note: row.note } : {}) });

class PostgreSqlInventoryScopeRepository implements InventoryScopeRepository {
  constructor(private readonly database: PlatformDatabase) {}
  async findBranch(workspaceId: string, branchId: string) { const rows = await this.database.select({ status: workspaceBranchReferences.status }).from(workspaceBranchReferences).where(and(eq(workspaceBranchReferences.workspaceId, workspaceId), eq(workspaceBranchReferences.branchId, branchId))).limit(1); return rows[0] ? { status: rows[0].status as "Active" | "Inactive" } : null; }
  async findProduct(workspaceId: string, productId: string) { const rows = await this.database.select({ lifecycleState: catalogProducts.lifecycleState }).from(catalogProducts).where(and(eq(catalogProducts.workspaceId, workspaceId), eq(catalogProducts.productId, productId))).limit(1); return rows[0] ?? null; }
}

class PostgreSqlInventoryRepository implements InventoryRepository {
  constructor(private readonly database: PlatformDatabase) {}
  async getBalance(workspaceId: string, branchId: string, productId: string) { const rows = await this.database.select().from(inventoryBalances).where(and(eq(inventoryBalances.workspaceId, workspaceId), eq(inventoryBalances.branchId, branchId), eq(inventoryBalances.productId, productId))).limit(1); return rows[0] ? balance(rows[0]) : null; }
  async lockBalance(workspaceId: string, branchId: string, productId: string, now: Date) { await this.database.insert(inventoryBalances).values({ workspaceId, branchId, productId, updatedAt: now }).onConflictDoNothing(); const rows = await this.database.select().from(inventoryBalances).where(and(eq(inventoryBalances.workspaceId, workspaceId), eq(inventoryBalances.branchId, branchId), eq(inventoryBalances.productId, productId))).limit(1).for("update"); if (!rows[0]) throw new Error("InventoryBalanceUnavailable"); return balance(rows[0]); }
  async saveBalance(value: InventoryBalance, expectedRevision: number) { const rows = await this.database.update(inventoryBalances).set({ onHandQuantity: value.onHand, reservedQuantity: value.reserved, damagedQuantity: value.damaged, revision: value.revision, updatedAt: value.updatedAt }).where(and(eq(inventoryBalances.workspaceId, value.workspaceId), eq(inventoryBalances.branchId, value.branchId), eq(inventoryBalances.productId, value.productId), eq(inventoryBalances.revision, expectedRevision))).returning({ revision: inventoryBalances.revision }); return rows.length === 1; }
  async appendMovement(value: InventoryMovement) { await this.database.insert(inventoryMovements).values({ workspaceId: value.workspaceId, branchId: value.branchId, movementId: value.movementId, productId: value.productId, movementType: value.movementType, quantity: value.quantity, occurredAt: value.occurredAt, createdAt: value.createdAt, createdByActorId: value.createdByActorId, operationId: value.operationId, reservationId: value.reservationId ?? null, correlationId: value.correlationId ?? null, reasonCode: value.reasonCode ?? null, note: value.note ?? null }); }
  async listMovements(workspaceId: string, branchId: string, productId: string, limit: number) { const rows = await this.database.select().from(inventoryMovements).where(and(eq(inventoryMovements.workspaceId, workspaceId), eq(inventoryMovements.branchId, branchId), eq(inventoryMovements.productId, productId))).orderBy(desc(inventoryMovements.occurredAt), desc(inventoryMovements.movementId)).limit(limit); return Object.freeze(rows.map(movement)); }
  async claimOperation(input: { readonly workspaceId: string; readonly operationId: string; readonly operationType: string; readonly fingerprint: string; readonly createdAt: Date }) { const inserted = await this.database.insert(inventoryOperations).values({ workspaceId: input.workspaceId, operationId: input.operationId, operationType: input.operationType, requestFingerprint: input.fingerprint, result: null, createdAt: input.createdAt }).onConflictDoNothing().returning({ operationId: inventoryOperations.operationId }); if (inserted.length) return { type: "Claimed" as const }; const rows = await this.database.select({ fingerprint: inventoryOperations.requestFingerprint, result: inventoryOperations.result }).from(inventoryOperations).where(and(eq(inventoryOperations.workspaceId, input.workspaceId), eq(inventoryOperations.operationId, input.operationId))).limit(1); if (!rows[0]) throw new Error("InventoryOperationUnavailable"); return { type: "Existing" as const, fingerprint: rows[0].fingerprint, result: rows[0].result }; }
  async completeOperation(workspaceId: string, operationId: string, result: Readonly<Record<string, unknown>>) { await this.database.update(inventoryOperations).set({ result }).where(and(eq(inventoryOperations.workspaceId, workspaceId), eq(inventoryOperations.operationId, operationId))); }
  async createReservation(value: InventoryReservation) { await this.database.insert(inventoryReservations).values(value); }
  async findReservation(workspaceId: string, reservationId: string, forUpdate: boolean) { const query = this.database.select().from(inventoryReservations).where(and(eq(inventoryReservations.workspaceId, workspaceId), eq(inventoryReservations.reservationId, reservationId))).limit(1); const rows = forUpdate ? await query.for("update") : await query; return rows[0] ? reservation(rows[0]) : null; }
  async updateReservation(value: InventoryReservation) { await this.database.update(inventoryReservations).set({ remainingQuantity: value.remainingQuantity, status: value.status, updatedAt: value.updatedAt }).where(and(eq(inventoryReservations.workspaceId, value.workspaceId), eq(inventoryReservations.reservationId, value.reservationId))); }
}

class PostgreSqlInventoryAuditRepository implements InventoryAuditRepository { constructor(private readonly database: PlatformDatabase) {} async append(input: Parameters<InventoryAuditRepository["append"]>[0]) { await this.database.insert(securityAuditEvents).values({ workspaceId: input.workspaceId, auditId: randomUUID(), eventType: input.eventType, actorId: input.actorId, subjectActorId: null, resultCode: "Succeeded", metadata: input.metadata, occurredAt: input.occurredAt }); } }

export class PostgreSqlInventoryUnitOfWork implements InventoryUnitOfWork { constructor(private readonly database: PlatformDatabase) {} execute<T>(work: (context: InventoryTransactionContext) => Promise<T>): Promise<T> { return this.database.transaction(async (transaction) => { const database = transaction as unknown as PlatformDatabase; return work(Object.freeze({ scope: new PostgreSqlInventoryScopeRepository(database), inventory: new PostgreSqlInventoryRepository(database), audit: new PostgreSqlInventoryAuditRepository(database) })); }); } }
